// ─── MACRO REGIME DATA ────────────────────────────────────────────
// Managed by Atlas · แสดง 4-indicator Macro Regime Gate (VIX / Yield Curve /
// HY Credit Spreads / Fed Stance) + regime-call history ตาม CLAUDE.md
// § Macro Regime Gate + § Atlas Regime Recording
// กฎการเขียน: ห้ามแก้/ลบ entry เดิม — push entry ใหม่เข้า array เท่านั้น (append-only)
// เหตุผล: entry เก่าคือ audit trail ว่า Atlas เคย call regime อะไรไว้ ณ วันไหน
// Source ทุก entry: agent_notes/atlas/YYYY-MM-DD_regime.md (ตัวจริงในโค้ดฐาน)

const MACRO_LAST_UPDATED = "2026-09-25";

// เรียงตามลำดับเวลา (เก่า -> ใหม่) — dashboard จะ sort ใหม่ (ใหม่ -> เก่า) เอง
const MACRO_REGIME_HISTORY = [
  {
    date: "2026-05-21",
    indicators: {
      vix: { value: "18.06", classification: "RISK-ON" },
      yieldCurve: { value: "+54 bps", classification: "RISK-ON" },
      hySpread: { value: "~286 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold 3.50–3.75%, 1 cut priced 2026", classification: "RISK-ON" },
    },
    vote: "4/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "CIO Package 2026-05-21 — unanimous RISK-ON, no override",
    source: "agent_notes/atlas/2026-05-21_regime.md",
  },
  {
    date: "2026-05-30",
    indicators: {
      vix: { value: "~15.74", classification: "RISK-ON" },
      yieldCurve: { value: "+49 bps", classification: "RISK-ON" },
      hySpread: { value: "~271 bps", classification: "RISK-ON" },
      fedStance: { value: "Neutral/Hold — 65% hold prob June FOMC, no 2026 cuts seen by JPM", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Maintained from 2026-05-21 — Fed stance sole TC dissenter",
    source: "agent_notes/atlas/2026-05-30_regime.md",
  },
  {
    date: "2026-06-07",
    indicators: {
      vix: { value: "~18-20", classification: "RISK-ON" },
      yieldCurve: { value: "~+15-35 bps", classification: "RISK-ON" },
      hySpread: { value: "~310-350 bps", classification: "RISK-ON" },
      fedStance: { value: "4.25–4.50%, cuts priced 2026", classification: "RISK-ON" },
    },
    vote: "4/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Confirmed consistent with 2026-06-03 call",
    source: "agent_notes/atlas/2026-06-07_regime.md",
  },
  {
    date: "2026-06-13",
    indicators: {
      vix: { value: "19.25–19.44", classification: "RISK-ON" },
      yieldCurve: { value: "+0.40%", classification: "RISK-ON" },
      hySpread: { value: "~276 bps", classification: "RISK-ON" },
      fedStance: { value: "0 cuts priced 2026, hikes>cuts into 2027", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Tactical caution flagged (Fed dissenter + FOMC Jun 16-17 binary) — majority not overridden",
    source: "agent_notes/atlas/2026-06-13_regime.md",
  },
  {
    date: "2026-06-14",
    indicators: {
      vix: { value: "17.68", classification: "RISK-ON" },
      yieldCurve: { value: "+40 bps", classification: "RISK-ON" },
      hySpread: { value: "~276 bps", classification: "RISK-ON" },
      fedStance: { value: "0 cuts priced, hikes > cuts", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Max policy: hold new deploys until FOMC June 16-17 passes despite RISK-ON call",
    source: "agent_notes/atlas/2026-06-14_regime.md",
  },
  {
    date: "2026-06-16",
    indicators: null,
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Price-only reconciliation session (Max) — references 2026-06-13 formal call, not re-run",
    source: "agent_notes/atlas/2026-06-16_regime.md",
  },
  {
    date: "2026-06-17",
    indicators: {
      vix: { value: "16.20", classification: "RISK-ON" },
      yieldCurve: { value: "~+0.40%", classification: "RISK-ON" },
      hySpread: { value: "~276 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold 3.50–3.75% (FOMC decision day, Warsh 1st presser), hawkish bias", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "FOMC decision day — Dot Plot binary event, Max held dry powder pending outcome",
    source: "agent_notes/atlas/2026-06-17_regime.md",
  },
  {
    date: "2026-06-24",
    indicators: null,
    vote: "STALE — 2 sessions overdue",
    regime: "TRANSITIONAL-CAUTIOUS (interim, unconfirmed)",
    override: "Preliminary read only — Fed dot-plot flipped hawkish (post-FOMC Jun 17, median 3.8%, 9/18 favor hike) + global AI/chip de-rating (KOSPI -9.99%, Nasdaq -2.21%) — full re-call not yet run, Max treats as defensive/uncertain until formal re-call",
    note: "Regime re-call overdue 2 sessions since 2026-06-13 formal call",
    source: "agent_notes/atlas/2026-06-24_regime.md",
  },
  {
    date: "2026-06-27",
    indicators: null,
    vote: "STALE — 3 sessions overdue",
    regime: "TRANSITIONAL-CAUTIOUS (interim, unconfirmed)",
    override: "Strong preliminary read: Fed dot-plot hawkish (PCE revised to 3.6%) + AI-trade de-rating week (KOSPI -9.99%, Nasdaq -4% week, $2.7T evaporated) — Max held defensive pending full re-call",
    note: "Regime re-call overdue 3 sessions — urgent flag",
    source: "agent_notes/atlas/2026-06-27_regime.md",
  },
  {
    date: "2026-07-02",
    indicators: {
      vix: { value: "16.59", classification: "RISK-ON" },
      yieldCurve: { value: "~+0.4% (10Y 4.47%, 2Y ~4.0%)", classification: "RISK-ON" },
      hySpread: { value: "263 bps (near cycle low)", classification: "RISK-ON" },
      fedStance: { value: "Hold 70-79% priced Jul 29, dot-plot hawkish vs weak June jobs (57k)", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Full re-call closing 4-session STALE gap — weak jobs report offset hawkish dot-plot scare; Force Deploy reactivated",
    source: "agent_notes/atlas/2026-07-02_regime.md",
  },
  {
    date: "2026-07-05",
    indicators: null,
    vote: "3/4 RISK-ON (unchanged)",
    regime: "RISK-ON",
    override: null,
    note: "No re-call — markets closed Jul 3-6, references 2026-07-02 call",
    source: "agent_notes/atlas/2026-07-05_regime.md",
  },
  {
    date: "2026-07-06",
    indicators: {
      vix: { value: "16.59 (Jul 2 close, holiday)", classification: "RISK-ON" },
      yieldCurve: { value: "+35 bps", classification: "RISK-ON" },
      hySpread: { value: "263 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold 3.50–3.75%; 2026 dot revised up to 3.8%, 9/18 favor ≥1 hike", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "No new trading day (holiday week) — confirms 2026-07-02 read",
    source: "agent_notes/atlas/2026-07-06_regime.md",
  },
  {
    date: "2026-07-12",
    indicators: {
      vix: { value: "15.03", classification: "RISK-ON" },
      yieldCurve: { value: "+35 bps", classification: "RISK-ON" },
      hySpread: { value: "267 bps", classification: "RISK-ON" },
      fedStance: { value: "Hawkish — no cut until Q2 2027, hike-by-Sept 68.8%, Dec 85.3%", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Downgraded quality note: \"RISK-ON with defensive tilt\" — not a formal override",
    source: "agent_notes/atlas/2026-07-12_regime.md",
  },
  {
    date: "2026-07-22",
    indicators: {
      vix: { value: "18.77", classification: "RISK-ON" },
      yieldCurve: { value: "+39 bps", classification: "RISK-ON" },
      hySpread: { value: "269-271 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold expected Jul 29, 0% cut priced, 3 hikes priced Sep/Oct/Dec (Warsh Fed)", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: null,
    source: "agent_notes/atlas/2026-07-22_regime.md",
  },
  {
    date: "2026-07-29",
    indicators: {
      vix: { value: "18.67", classification: "RISK-ON" },
      yieldCurve: { value: "+34 bps", classification: "RISK-ON" },
      hySpread: { value: "281 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold expected (FOMC today), futures path rising to ~3.8-4% by year-end", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "FOMC decision day + intercepted Iran attack on US troops (oil +5%) — market absorbed without VIX spike, no override applied",
    source: "agent_notes/atlas/2026-07-29_regime.md",
  },
  {
    date: "2026-08-01",
    indicators: null,
    vote: "N/A — not re-called this session",
    regime: "RISK-ON 3/4 (referenced, 20 days stale)",
    override: null,
    note: "Portfolio Review price-only session — full re-call overdue since 2026-07-12",
    source: "agent_notes/atlas/2026-08-01_regime.md",
  },
  {
    date: "2026-08-02",
    indicators: {
      vix: { value: "15.99 (Jul 31), 17.09 (Jul 30)", classification: "RISK-ON" },
      yieldCurve: { value: "+45 bps (30Y hit 5.28%, highest since 2007)", classification: "RISK-ON" },
      hySpread: { value: "281-284 bps", classification: "RISK-ON" },
      fedStance: { value: "FOMC held 3.50–3.75% (9-3 vote, 3 dissents for hike), Sept cut odds 54.4%", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Urgent re-call ordered by Max (21-day gap) — labeled \"RISK-ON with elevated tail-risk watch\" due to long-end yield sell-off quality concern; no override",
    source: "agent_notes/atlas/2026-08-02_regime.md",
  },
  {
    date: "2026-08-05",
    indicators: {
      vix: { value: "16.54", classification: "RISK-ON" },
      yieldCurve: { value: "+42 bps", classification: "RISK-ON" },
      hySpread: { value: "~281-284 bps", classification: "RISK-ON" },
      fedStance: { value: "Ambiguous — Sept cut odds 48-65% vs Jul hike-spike 68.8%; no cuts before 2027 per minutes", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Supersedes 2026-07-12 (24 days stale) — same 3/4 RISK-ON outcome",
    source: "agent_notes/atlas/2026-08-05_regime.md",
  },
  {
    date: "2026-08-09",
    indicators: null,
    vote: "N/A — price verification only",
    regime: "RISK-ON 3/4 (referenced)",
    override: null,
    note: "Portfolio Review price-only session, references 2026-08-05 formal call",
    source: "agent_notes/atlas/2026-08-09_regime.md",
  },
  {
    date: "2026-08-10",
    indicators: {
      vix: { value: "14.90", classification: "RISK-ON" },
      yieldCurve: { value: "+45 bps", classification: "RISK-ON" },
      hySpread: { value: "271-273 bps", classification: "RISK-ON" },
      fedStance: { value: "Mixed — dot plot hawkish (3.8% year-end) but weak July jobs (-23K) pushed dovish shift", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "3rd consecutive RISK-ON confirmation (07-12 → 08-05 interim → 08-10 formal)",
    source: "agent_notes/atlas/2026-08-10_regime.md",
  },
  {
    date: "2026-08-20",
    indicators: {
      vix: { value: null, classification: null },
      yieldCurve: { value: "+45 bps", classification: "RISK-ON" },
      hySpread: { value: "~271-281 bps", classification: "RISK-ON" },
      fedStance: { value: "2×25bps hikes priced Sept + Dec 2026 (median year-end 3.8%) — flipped from mid-2026 cut expectation", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "CIO-provided verified data package, cross-checked against Fed funds futures",
    source: "agent_notes/atlas/2026-08-20_regime.md",
  },
  {
    date: "2026-08-21",
    indicators: {
      vix: { value: "14.89", classification: "RISK-ON" },
      yieldCurve: { value: "+35 bps", classification: "RISK-ON" },
      hySpread: { value: "~271-281 bps", classification: "RISK-ON" },
      fedStance: { value: "Ambiguous/split — no clear majority direction, not counted", classification: "TRANSITIONAL-CAUTIOUS" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "10Y volatility (4.75%→4.70%) monitored, no override — S&P forward P/E ~20x, breadth 56.8% >200MA, no overheating signal",
    source: "agent_notes/atlas/2026-08-21_regime.md",
  },
  {
    date: "2026-08-22",
    indicators: null,
    vote: "N/A — price-only",
    regime: "RISK-ON 3/4 (referenced)",
    override: null,
    note: "Portfolio Review Mode 3 — references 2026-08-21 formal call, no new indicator vote",
    source: "agent_notes/atlas/2026-08-22_regime.md",
  },
  {
    date: "2026-08-27",
    indicators: {
      vix: { value: "15.21", classification: "RISK-ON" },
      yieldCurve: { value: "+45 bps", classification: "RISK-ON" },
      hySpread: { value: "~275 bps", classification: "RISK-ON" },
      fedStance: { value: "Hold 3.50–3.75% (5th straight), but market pricing 2 hikes Sep/Dec 2026", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Fed hold (not an actual hike) judged insufficient to override majority — forward pricing only",
    source: "agent_notes/atlas/2026-08-27_regime.md",
  },
  {
    date: "2026-08-28",
    indicators: {
      vix: { value: "15.13", classification: "RISK-ON" },
      yieldCurve: { value: "+44 bps", classification: "RISK-ON" },
      hySpread: { value: "~281 bps", classification: "RISK-ON" },
      fedStance: { value: "Easing — effective funds ~3.63%, cuts priced 12M forward", classification: "RISK-ON" },
    },
    vote: "4/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Unanimous RISK-ON — but HY spreads ~281bps flagged as richest-decile credit complacency (context caveat, no regime change)",
    source: "agent_notes/atlas/2026-08-28_regime.md",
  },
  {
    date: "2026-08-29",
    indicators: {
      vix: { value: null, classification: null },
      yieldCurve: { value: "+44 bps (2Y 4.24%, 10Y 4.68%, 30Y 5.20%)", classification: "RISK-ON" },
      hySpread: { value: "~281 bps", classification: "RISK-ON" },
      fedStance: { value: "Hawkish shift — Chair Warsh Jackson Hole: PCE 3.7% YoY, \"trends have not meaningfully improved\"; Sept hike odds 48-59%", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Regime declared \"RISK-ON with Fed-hawkish cautionary overlay\" after Warsh Jackson Hole speech",
    source: "agent_notes/atlas/2026-08-29_regime.md",
  },
  {
    date: "2026-08-30",
    indicators: {
      vix: { value: null, classification: null },
      yieldCurve: { value: "+44 bps (2Y 4.24%, 10Y 4.68%)", classification: "RISK-ON" },
      hySpread: { value: "~281 bps", classification: "RISK-ON" },
      fedStance: { value: "Hawkish — Warsh Jackson Hole tone maintained, Sept hike odds ~48-59% coin-flip", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Confirms 2026-08-29 read — \"RISK-ON with Fed-hawkish cautionary overlay\"",
    source: "agent_notes/atlas/2026-08-30_regime.md",
  },
  {
    date: "2026-09-01",
    indicators: {
      vix: { value: "14.43 (Aug 31 close, 2026 low)", classification: "RISK-ON" },
      yieldCurve: { value: "+44 bps (stale, pre-shock — Aug 28 print)", classification: "RISK-ON" },
      hySpread: { value: "~275-285 bps (stale, pre-shock)", classification: "RISK-ON" },
      fedStance: { value: "Hawkish — 25bp hike priced for Sept FOMC, CME FedWatch 60-82% odds", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "TRANSITIONAL-CAUTIOUS",
    override: "JUDGMENT OVERRIDE applied — US-Iran military escalation (Aug 31 strikes on Iranian soil + Strait of Hormuz tail risk), sticky CPI 3.4% YoY, and stale pre-shock RISK-ON reads (yield curve/HY printed before the Aug 31 strike) outweigh the mechanical 3/4 majority",
    note: "First override of this window — ZETA analysis session",
    source: "agent_notes/atlas/2026-09-01_regime.md",
  },
  {
    date: "2026-09-03",
    indicators: {
      vix: { value: "16.34-16.81", classification: "RISK-ON" },
      yieldCurve: { value: "+40-41 bps", classification: "RISK-ON" },
      hySpread: { value: "265 bps", classification: "RISK-ON" },
      fedStance: { value: "~66.2% odds of hike at Sept FOMC, zero cuts priced into 2028", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "TRANSITIONAL-CAUTIOUS",
    override: "Override maintained — Fed Stance judged a leading (not coincident) indicator with 13 days to FOMC; equity risk premium compressed to +18bps vs historical 300-400bps norm; consistent with 2026-09-01 override rationale (situation not resolved)",
    note: "FSLR analysis session (Scout Round 27)",
    source: "agent_notes/atlas/2026-09-03_regime.md",
  },
  {
    date: "2026-09-04",
    indicators: {
      vix: { value: "~14.3-15.2", classification: "RISK-ON" },
      yieldCurve: { value: "+43 bps", classification: "RISK-ON" },
      hySpread: { value: "~265 bps", classification: "RISK-ON" },
      fedStance: { value: "~65% odds of 25bp hike Sept 15-16 FOMC", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "TRANSITIONAL-CAUTIOUS",
    override: "Override maintained — US-Iran conflict escalated further (CENTCOM struck additional targets Sept 1, Iran retaliated against 5 countries), Hormuz throughput collapsed to 4.9M bbl/day (from ~20M pre-conflict); S&P resilience (+1.06%) noted but insufficient to flip",
    note: "CNC analysis session (Scout Round 27 #2)",
    source: "agent_notes/atlas/2026-09-04_regime.md",
  },
  {
    date: "2026-09-05",
    indicators: {
      vix: { value: "16.34", classification: "RISK-ON" },
      yieldCurve: { value: "+40 to +44 bps", classification: "RISK-ON" },
      hySpread: { value: "265 bps", classification: "RISK-ON" },
      fedStance: { value: "88.8% market-implied odds of zero rate cuts in 2026, PCE ~3.6-3.7%", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "No override applied this call — per house rule majority governs when hard indicators show no distress; flagged as a watch item (\"Fed Stance may be the leading indicator of a regime shift, not the outlier\")",
    source: "agent_notes/atlas/2026-09-05_regime.md",
  },
  {
    date: "2026-09-11",
    indicators: {
      vix: { value: "16.46", classification: "RISK-ON" },
      yieldCurve: { value: "+40 bps (10Y ~4.85%, highest since Nov 2023)", classification: "RISK-ON" },
      hySpread: { value: "265 bps", classification: "RISK-ON" },
      fedStance: { value: ">73% odds of 25bp hike Sept 15-16 FOMC (post-PPI), zero cuts priced into 2028", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "TRANSITIONAL-CAUTIOUS",
    override: "Override applied — Brent broke $100-102 (US destroyed 3-5 Iranian tankers, Hormuz flows <2M bpd), twin binary events (CPI same day + FOMC Sept 16), S&P down 4 consecutive sessions, reconciles standing portfolio.js TC discrepancy",
    note: "Formalizes TC; next mandatory re-call within 1 session of Sept 16 FOMC outcome",
    source: "agent_notes/atlas/2026-09-11_regime.md",
  },
  {
    date: "2026-09-13",
    indicators: null,
    vote: "N/A — price reconciliation only",
    regime: "TRANSITIONAL-CAUTIOUS (unchanged, referenced from 2026-09-11)",
    override: null,
    note: "S&P 500 Single Source of Truth correction session — not a regime re-call",
    source: "agent_notes/atlas/2026-09-13_regime.md",
  },
  {
    date: "2026-09-15",
    indicators: null,
    vote: "N/A — price verification only",
    regime: "TRANSITIONAL-CAUTIOUS (unchanged, referenced from 2026-09-11)",
    override: null,
    note: "Pre-FOMC price verification — CME FedWatch showed ~56% hike odds (lower than the >73% used 09-11, dates not directly comparable, flagged for cross-check)",
    source: "agent_notes/atlas/2026-09-15_regime.md",
  },
  {
    date: "2026-09-20",
    indicators: {
      vix: { value: "14.81 (Sept 18 close)", classification: "RISK-ON" },
      yieldCurve: { value: "+33 bps", classification: "RISK-ON" },
      hySpread: { value: "276 bps", classification: "RISK-ON" },
      fedStance: { value: "REALIZED — FOMC hiked +25bps to 3.75-4.00% on Sept 16 (first hike in 3+ years, 12-0 unanimous); 16/18 officials expect ≥1 more hike", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "TRANSITIONAL-CAUTIOUS",
    override: "Override maintained (mandatory post-FOMC re-call) — the FOMC resolved hawkish, not dovish as the 09-11 flip-back condition required; Brent still ~$103 (unresolved); FOMC week equities net negative-to-flat outside mega-cap tech",
    note: "Mandatory post-FOMC re-call, attached to LVS analysis session",
    source: "agent_notes/atlas/2026-09-20_regime.md",
  },
  {
    date: "2026-09-25",
    indicators: {
      vix: { value: "14.21 (FRED close Sept 22)", classification: "RISK-ON" },
      yieldCurve: { value: "+0.25 (Sept 22, not inverted)", classification: "RISK-ON" },
      hySpread: { value: "2.66-2.73% (tight, no stress)", classification: "RISK-ON" },
      fedStance: { value: "HAWKISH — FOMC hiked +25bp to 3.75-4.00% (Sept 16), signaled another hike coming", classification: "RISK-OFF" },
    },
    vote: "3/4 RISK-ON",
    regime: "RISK-ON",
    override: null,
    note: "Re-call requested by CIO before executing DECK BUY signal — supersedes stale TC/Force-Deploy-Suspended record; \"RISK-ON 3/4 with defensive/hedge tilt\" due to hawkish Fed dissent (same pattern as 2026-07-12)",
    source: "agent_notes/atlas/2026-09-25_regime.md",
  },
];
