// ─── SECTOR VIEWS DATA ───────────────────────────────────────────
// Managed by Atlas · เขียนแบบ ad-hoc เมื่อทีมเกิด/ทบทวน view ระดับ sector เท่านั้น
// (ไม่ใช่ scheduled job แบบ /news-scan — ดู CLAUDE.md § Sector Views Protocol)
// กฎการเขียน: ห้ามแก้/ลบ entry เดิม — push entry ใหม่เข้า array เท่านั้น (append-only)
// เหตุผล: entry เก่าคือ audit trail ว่าทีมเคยคิดอะไรมาก่อน ณ วันไหน — การแก้ทับจะทำลายหลักฐานนั้น

const SECTOR_VIEWS_LAST_UPDATED = "2026-08-10 12:00";

const SECTOR_VIEWS = [
  {
    sector: "Energy",
    slug: "energy",
    stance: "NEGATIVE",
    cyclePosition: "Late-cycle",
    headline: "Late-cycle plateau เงินทุนใหม่เสี่ยงจ่ายที่จุดพีค — รอ de-escalation ก่อน",
    thesis: "พลังงานอยู่ช่วง late-cycle ที่ราคาถูกดันขึ้นด้วย geopolitical risk premium (Iran conflict, oil +5% แตะ $83+ วันเดียว) มากกว่า fundamental scarcity — สัญญาณชัดที่สุดคือ S&P 500 Energy earnings คาดโต +57% ปี 2026 แต่ consensus คาดหดตัว -5% ปี 2027 (pattern peak-then-decline ที่ตลาด price-in แล้ว) ประกอบกับ XLE พุ่ง +32-40% YTD ทิ้งห่าง S&P 500 และ Tech จนถูกมองว่า valuation ตึงเกินไปแล้ว ขณะที่ EIA/ING คาด oversupply 2.0-2.26 ล้านบาร์เรล/วันปี 2026 ซึ่งขัดแย้งกับราคาที่พุ่งอยู่ตอนนี้ — capex ยังมีวินัย (upstream ลดต่อเนื่องปีที่ 2) และ rig count ยังต่ำเทียบ shale-boom era จึงยังไม่ใช่ bubble-top แบบสุดขั้ว แต่การซื้อตอนนี้เท่ากับจ่ายที่ earnings peak + valuation แพง + geopolitical premium พร้อมกันทั้งสามอย่าง ซึ่งเสี่ยงเกินไปสำหรับ time horizon 3-5 ปีของกองทุน",
    keyPoints: [
      "S&P 500 Energy earnings: +57% (2026F) แล้วพลิกหด -5% (2027F) — สัญญาณ peak-then-decline จากตลาดเอง",
      "XLE +32-40% YTD 2026 (ทิ้งห่าง S&P 500 +8.8% และ Tech +23%) — valuation ตึงแล้ว, risk/reward tilted downside ตาม analyst",
      "EIA/ING คาด oversupply 2.0-2.26 ล้านบาร์เรล/วันปี 2026 — ราคาปัจจุบันขับเคลื่อนด้วย Iran conflict premium ไม่ใช่ scarcity จริง",
      "Upstream capex ลดต่อเนื่องปีที่ 2 (-2-3% YoY) + rig count ยังต่ำเทียบ shale-boom — ยังไม่ใช่ euphoria-style bubble top",
      "ถ้าจะพิจารณาจริง: integrated majors (XOM/CVX) หรือ midstream/pipeline (FCF นิ่งกว่า) ดีกว่า pure-play E&P ที่จะโดนแรงสุดถ้า cycle หัน",
    ],
    metrics: [
      { label: "Energy earnings growth 2026F", value: 57 },
      { label: "Energy earnings growth 2027F", value: -5 },
      { label: "XLE YTD return", value: 32 },
      { label: "S&P 500 YTD return", value: 8.8 },
    ],
    relatedTickers: [],
    sources: [
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "GuruFocus — Energy Sector Insights: Key Pivot Points for XLE", url: "https://www.gurufocus.com/news/8980339/energy-sector-insights-key-pivot-points-for-xle" },
      { title: "ING Think — Bearish oil outlook, but upside risks abound", url: "https://think.ing.com/articles/bearish-oil-outlook-but-clear-upside-risks/" },
      { title: "Bloomberg — OPEC Keeps 2026 Oil Supply, Demand Outlook Steady", url: "https://www.bloomberg.com/news/articles/2025-12-11/opec-data-point-to-balanced-global-oil-market-in-2026" },
      { title: "OilPrice — Global Upstream Capex Set To Fall Again In 2026 Amid Low Oil Prices", url: "https://oilprice.com/Energy/Crude-Oil/Global-Upstream-Capex-Set-To-Fall-Again-In-2026-Amid-Low-Oil-Prices.html" },
      { title: "Bloomberg — US Oil Rig Count Rises for 12th Week, Longest Streak Since 2022", url: "https://www.bloomberg.com/news/articles/2026-07-17/us-oil-rig-count-notches-longest-streak-without-drop-since-2022" },
      { title: "EIA — Weekly Petroleum Status Report (crude inventories)", url: "https://www.eia.gov/todayinenergy/detail.php?id=67868" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — energy sector cycle analysis",
  },
  {
    sector: "Software / AI",
    slug: "software-ai",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle",
    headline: "Secular growth ของจริง แต่ ROI-realization overhang กดราคาเป็นระลอก — selective ไม่ broad-avoid",
    thesis: "AI capex ของ hyperscaler ยังโตต่อเนื่องแรงมาก (4 รายใหญ่ guide รวม $670B ปี 2026, US Big Tech investment คาดโต +50% ทะลุ $600B, capex intensity ~23% ของ revenue สูงกว่ายุคก่อน ChatGPT กว่าเท่าตัว) แต่ประเด็นหลักที่ตลาดยังตัดสินใจไม่ได้คือช่องว่างระหว่างเงินที่ลงทุนกับ ROI ที่วัดผลได้จริง — Morgan Stanley เรียกช่วงนี้ว่า 'peak uncertainty' หลัง valuation กลุ่ม software/services ร่วงกลับมาใกล้ระดับที่เคยเห็นตอน disruption scare ครั้งก่อน สอดคล้องกับที่พอร์ตเราเจอเองปีนี้ (ADBE/CRM โดน downgrade เรื่อง capex-ROI overhang ก่อนจะเด้งกลับ, GOOGL stopDist เกือบ breach เพราะตลาด sell-the-news ทุกครั้งที่ capex guide ขึ้น แม้ Cloud growth จริงจะเร่งขึ้นต่อเนื่อง). ทีมยังไม่ avoid ทั้งกลุ่มเพราะ backlog/cloud growth เป็นหลักฐาน ROI ที่จับต้องได้จริงสำหรับผู้ชนะที่ชัดเจน (เช่น GOOGL Cloud +82%) แต่ยังไม่ commit เพิ่มทุนใหม่แบบไม่เลือกหน้า เพราะ mass productive deployment ในระดับ enterprise ยังไม่มาจริงตามที่ capex บอกไว้",
    keyPoints: [
      "4 hyperscaler ใหญ่ guide capex รวม $670B ปี 2026, US Big Tech +50% ทะลุ $600B, capex intensity ~23% ของ revenue",
      "Morgan Stanley: software/services valuation กลับมาใกล้ 'peak uncertainty' ระดับเดียวกับ disruption scare ครั้งก่อน",
      "ช่องว่าง capex-vs-ROI คือ bull/bear pivot หลักของกลุ่มทั้งปี 2026-2027 — mass enterprise deployment ยังไม่มาจริง",
      "หลักฐานเชิงประจักษ์จากพอร์ตเราเอง: ADBE/CRM/GOOGL ทั้งหมดโดน sell-the-news ซ้ำๆ ทุกครั้งที่มีข่าว capex แม้ fundamentals จริงจะแข็งแกร่งขึ้นต่อเนื่อง",
      "Technology sector Q2 2026 earnings +64.6% YoY (เร่งขึ้น) ยืนยันว่า demand ยังจริง ไม่ใช่แค่ hype — แต่ market ยัง discount ด้วย ROI doubt",
    ],
    metrics: [
      { label: "US Big Tech capex growth (YoY)", value: 50 },
      { label: "Capex intensity (% of revenue)", value: 23 },
      { label: "Technology sector Q2 2026 earnings growth", value: 64.6 },
    ],
    relatedTickers: ["ADBE", "NOW", "GOOGL", "CRM", "ADSK"],
    sources: [
      { title: "CNBC — AI boom: Big Tech capex now seen topping $1 trillion in 2027", url: "https://www.cnbc.com/2026/04/30/ai-boom-big-tech-capital-expenditures-now-seen-topping-1-trillion-in-2027-.html" },
      { title: "Goldman Sachs — Why AI Companies May Invest More than $500 Billion in 2026", url: "https://www.goldmansachs.com/insights/articles/why-ai-companies-may-invest-more-than-500-billion-in-2026" },
      { title: "PwC — Technology: US Deals 2026 midyear outlook", url: "https://www.pwc.com/us/en/industries/tmt/library/technology-deals-outlook.html" },
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — sector coverage expansion (portfolio is 6/8 positions Software/AI-adjacent)",
  },
  {
    sector: "Healthcare",
    slug: "healthcare",
    stance: "CAUTIOUS",
    cyclePosition: "Late-cycle / Defensive rotation",
    headline: "Valuation ถูก + rotation story น่าสนใจ แต่ earnings ยังหดตัวจริง และมี stock-specific risk ในพอร์ตเราเอง",
    thesis: "Sell-side หลายสำนัก (Janus Henderson, BlackRock iShares, Bloomberg) มองปี 2026 เป็นปีที่ healthcare 'กลับมา' ได้ — valuation ยังอยู่ใกล้จุดต่ำสุดในรอบ ~30 ปีจาก policy uncertainty ที่เริ่มคลี่คลาย (drug pricing reform ชัดเจนขึ้น, M&A เริ่มกลับมาคึกคัก) และเป็น sector defensive ที่มักได้ประโยชน์จาก rotation ช่วงปลายวัฏจักร แต่ข้อมูลจริงจาก Q2 2026 earnings season ขัดแย้งกับ narrative นี้ชัดเจน — FactSet รายงานว่า healthcare เป็น sector เดียวใน S&P 500 ที่ earnings หดตัว YoY ไตรมาสนี้ และหดตัวหนักที่สุดในบรรดาทุก sector ที่ -18.2% (แย่กว่าคาดการณ์เดิม -9.5% ก่อนหน้านี้) สาเหตุหลักมาจาก managed care/health insurer เจอ patient utilization สูงเกินคาด + ค่าใช้จ่ายยา GLP-1 พุ่ง ไม่ใช่แค่ sentiment ที่แย่ ทีมเจอสัญญาณ stock-specific คล้ายกันในพอร์ต/watchlist ของเราเอง: REGN เจอ securities class action lawsuit ใหม่ (Phase 3 melanoma setback), ZTS growth ชะลอเหลือ 2-5% พร้อม analyst PT ถูกหั่นต่อเนื่อง 2 รอบ, DXCM มีประวัติ crash -40% ในไตรมาสเดียวกันเมื่อ 2 ปีก่อน — ทำให้ยังไม่มั่นใจพอจะเรียกทั้ง sector ว่า positive แม้ valuation จะน่าสนใจ",
    keyPoints: [
      "Valuation healthcare ใกล้จุดต่ำสุดรอบ ~30 ปี จาก policy uncertainty ที่เริ่มคลี่คลาย (drug pricing reform, Medicare Advantage rate decision เม.ย.)",
      "Q2 2026: healthcare earnings -18.2% YoY (FactSet) — แย่ที่สุดในบรรดาทุก sector ของ S&P 500 และแย่กว่าคาดการณ์เดิม -9.5% ต้นเหตุจาก managed care/GLP-1 cost surge",
      "M&A activity เริ่มกลับมาคึกคักขึ้น เป็นสัญญาณบวกเชิง structural",
      "Stock-specific risk ในพอร์ต/watchlist เราเอง: REGN lawsuit ใหม่, ZTS growth deceleration + PT cuts 2 รอบ, DXCM มี crash pattern -40% ประวัติศาสตร์ก่อน earnings",
      "สรุป: เป็น sector ที่ 'น่าดูใกล้ชิด' ไม่ใช่ 'รีบเพิ่มทุน' — รอดู Q3 earnings ว่า decline เป็น trough จริงหรือแค่เริ่มต้น",
    ],
    metrics: [
      { label: "Healthcare Q2 2026 earnings growth", value: -18.2 },
      { label: "S&P 500 overall Q2 2026 earnings growth", value: 24.5 },
    ],
    relatedTickers: ["REGN", "DXCM", "ZTS", "PODD"],
    sources: [
      { title: "Bloomberg — Healthcare Looks Ready to Star in Rotation Trade", url: "https://www.bloomberg.com/news/articles/2026-07-13/healthcare-looks-ready-to-star-in-rotation-trade-taking-stock" },
      { title: "Janus Henderson — Why healthcare stocks could excel in 2026", url: "https://www.janushenderson.com/article/why-healthcare-stocks-could-excel-in-2026/" },
      { title: "BlackRock iShares — Healthcare making a comeback?", url: "https://www.blackrock.com/au/insights/ishares/2026-comeback-year-for-healthcare" },
      { title: "Forbes — S&P 500 Earnings Outlook (healthcare sole YoY earnings decline)", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "ETF Trends — Q2 Earnings Preview: Tech & Energy Drive Growth Amid Healthcare Headwinds", url: "https://www.etftrends.com/sector-investing-content-hub/q2-earnings-preview-tech-energy-drive-growth-amid-healthcare-headwinds/" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — sector coverage expansion (portfolio holds REGN + DXCM/ZTS/PODD watchlist)",
  },
  {
    sector: "Energy",
    slug: "energy",
    stance: "NEGATIVE",
    cyclePosition: "Late-cycle",
    headline: "War premium ยังไม่นิ่ง — Brent ดีดกลับ $89-90 ปลาย ก.ค. (ไม่ใช่ $76 ตามที่ brief เข้าใจ) เทคนิคเริ่มอ่อนตัว ยืนยัน 'รอ' ไม่ใช่ 'เข้า'",
    thesis: "อัปเดตต่อยอด entry Energy เดิม (30 ก.ค. 2026, NEGATIVE) จาก brief ของ CIO/Bear ที่ขอให้ verify war timeline + technical signals + ตัวเลขที่ยังไม่ยืนยัน — ทีม WebFetch หลายแหล่ง (TradingEconomics, OilPrice.com futures, CNBC, Bloomberg) พบว่า ณ 29-30 ก.ค. 2026 Brent อยู่ที่ราว $89-90/bbl ไม่ใช่ $76-77 ตามที่ brief อ้าง เพราะเกิดการยกระดับความรุนแรงรอบใหม่ (สหรัฐฯ โจมตี Iran คืนวันที่ 29 ก.ค. ตอบโต้การโจมตีฐานทัพสหรัฐฯ, Iran ขู่ตอบโต้เพิ่ม, กลุ่มติดอาวุธหนุน Iran ยิงโดรนใส่โรงกลั่นซาอุฯ ต่อเนื่อง 2 วัน) หลัง ceasefire เดิมพังไปแล้วตั้งแต่ 8 ก.ค. timeline สงครามที่ verify แล้วก็คลาดเคลื่อนจาก brief หลายจุด: peak ราคาแรกอยู่ที่ $116.29/bbl วันที่ 9 มี.ค. (ไม่ใช่ช่วง 11-24 มี.ค.), ceasefire จริงครั้งแรกเกิด 7-8 เม.ย. ไม่ใช่ 23-31 มี.ค. ตามที่ brief อ้าง (มีแต่การเจรจา/บล็อกท่าเรือระหว่างนั้น ไม่มี ceasefire ในมี.ค.) จากนั้นขยายไม่มีกำหนด 21 เม.ย., เจรจา Islamabad ล้มเหลวกลาง เม.ย., เซ็น MOU 60 วันรอบใหม่ 17 มิ.ย. ก่อนพังอีกครั้ง 8 ก.ค. และ escalate ต่อเนื่องถึงปลาย ก.ค. — ทั้งหมดนี้ยืนยันว่าความเสี่ยงเป็น dual-direction จริงตามที่ brief เตือน สงครามยังไม่จบ ราคาสวิงได้ทั้งพุ่งแรงกว่านี้ถ้า Hormuz ปิดอีกรอบ และร่วงแรงถ้า de-escalate จริงจัง ไม่ใช่ downside scenario เดียวที่เคยเน้น ด้านเทคนิคของ XLE เริ่มส่งสัญญาณอ่อนตัวสอดคล้องกับความเสี่ยงนี้: Aroon เข้าสู่ downtrend ตั้งแต่ 13 ก.ค., RSI(14) เคยพุ่งถึง 85 (severely overbought) ก่อนหลุดจากโซน overbought เมื่อ 27 ก.ค. แม้จะมี bullish MA crossover (10dma ตัดขึ้นเหนือ 50dma เมื่อ 20 ก.ค.) แทรกอยู่ทำให้ signal ยังไม่ชี้ทางเดียวขาด แต่ momentum โดยรวมเริ่มเสีย ด้าน valuation หลัง verify จริงผ่าน stockanalysis.com: XLE ราคา $58.59 market cap ~$39.5B P/E 20.94 div yield 2.59% (ตรงกับตัวเลขที่ brief อ้างเกือบสนิท) YTD return อยู่ราว 30-35% แล้วแต่แหล่ง/วันวัด ส่วนคำถามที่ brief สงสัยเองว่า Tech comeback อาจทำให้ gap แคบลง ทีมตรวจแล้วพบว่าถูกทิศทางจริง — XLK ปีนี้ให้ผลตอบแทนประมาณ 33% ใกล้เคียง XLE มาก ต่างจาก entry เดิมที่ gap อยู่ราว 9-17 จุด แปลว่า gap แคบลงจริง แต่ตัวเลข quarter-specific ที่ brief อ้าง (XLK Q2 +43% large cap, Energy large cap -13%) หาแหล่งยืนยันไม่เจอเลยในทุกแหล่งที่ค้น จึงต้องระบุว่า unverified สำหรับตัวเลขนั้นโดยเฉพาะ ประเด็นที่สำคัญที่สุดคือตัวเลข earnings เดิม: +57% (2026F) / -5% (2027F) ที่ entry เก่าอ้างอิง Forbes — ทีม re-fetch บทความ Forbes ตรงๆ แล้วพบว่าบทความไม่มีตัวเลขนี้เลย มีแค่ข้อความว่า Energy นำ Q2 ตามด้วย Tech โดยไม่ระบุเปอร์เซ็นต์ และไม่มี forecast ปี 2027 เลย ตัวเลขจริงที่ verify ได้จาก FactSet คือ Energy earnings growth YoY: Q2 2026 +122.9% (สูงกว่าที่เคยอ้างมาก) ลดหลั่นเหลือ Q3 2026 +75.6%, Q4 2026 +69.5%, Q1 2027 +49.6% แล้วพลิกลบ Q2 2027 -26.3% — ยืนยัน pattern peak-then-decline เดียวกับ thesis เดิม เพียงแต่ magnitude ต่างจากที่เคยอ้างไว้มาก ทีมอื่นควรใช้ตัวเลขชุดนี้แทนตัวเลขเดิม ส่วน EIA oversupply 2.0-2.26 mb/d และ upstream capex -2 ถึง -3% YoY ที่ brief ขอให้ verify ทั้งสองผ่านตรงตามอ้าง (EIA คาด glut 2.2 mb/d ปี 2026, OilPrice.com ยืนยัน capex ลดต่อเนื่องปีที่ 2) สรุป: stance ยังคง NEGATIVE เหมือนเดิม แต่ต้อง update ว่าความเสี่ยงตอนนี้กำลัง escalate ไปในทิศ 'ราคาสูงกว่าที่คิด' ไม่ใช่ de-escalate ตามที่ brief เข้าใจตอนแรก — เข้าซื้อตอนนี้เสี่ยงจ่ายที่ war-premium peak ซ้อนกับ valuation ตึงและ momentum กำลังเสียพร้อมกันสามชั้น",
    keyPoints: [
      "Brent ปัจจุบัน (29-30 ก.ค. 2026) อยู่ที่ราว $89-90/bbl หลังยกระดับรุนแรงรอบใหม่ (สหรัฐฯ โจมตี Iran, Iran ขู่ตอบโต้, โดรนโจมตีโรงกลั่นซาอุฯ) — ไม่ใช่ $76-77 ตามที่ brief เข้าใจตอนแรก คลาดเคลื่อนจริง",
      "Timeline สงคราม verify แล้ว: เริ่ม 28 ก.พ. (Operation Epic Fury/Roaring Lion) → peak $116.29 วันที่ 9 มี.ค. → ceasefire จริงครั้งแรก 7-8 เม.ย. (ไม่ใช่มี.ค. ตามที่ brief อ้าง) → ขยายไม่มีกำหนด 21 เม.ย. → MOU รอบใหม่ 17 มิ.ย. → พังอีกครั้ง 8 ก.ค. → escalate ต่อเนื่องถึง 29-30 ก.ค.",
      "เทคนิคเริ่มอ่อนตัว: Aroon downtrend ตั้งแต่ 13 ก.ค., RSI(14) เคยแตะ 85 ก่อนหลุด overbought 27 ก.ค. — แม้มี bullish MA crossover แทรก signal ยังไม่ชี้ทางเดียวขาด",
      "ตัวเลข earnings เดิม +57%/-5% ที่อ้าง Forbes ไม่มีอยู่จริงในบทความ — ตัวเลข FactSet ที่ verify ได้คือ Q2 2026 +122.9% ลดหลั่นจนพลิกลบ -26.3% ใน Q2 2027 (peak-then-decline ยืนยัน แต่ magnitude ต่างจากเดิมมาก)",
      "EIA oversupply 2.2 mb/d และ upstream capex -2 ถึง -3% YoY verify ผ่านตรงตามอ้าง — gap XLE vs Tech แคบลงจริง (XLE YTD ~30-35% vs XLK ~33%) แต่ตัวเลข quarter-specific +43%/-13% หาแหล่งยืนยันไม่เจอ (unverified)",
    ],
    metrics: [
      { label: "Brent crude ปัจจุบัน (29-30 ก.ค. 2026, USD/bbl)", value: 89 },
      { label: "Brent crude พีคสงคราม (9 มี.ค. 2026, USD/bbl)", value: 116 },
      { label: "S&P 500 Energy earnings growth Q2 2026 (YoY %)", value: 122.9 },
      { label: "S&P 500 Energy earnings growth Q2 2027F (YoY %)", value: -26.3 },
    ],
    relatedTickers: ["XLE", "XOM", "CVX"],
    sources: [
      { title: "TradingEconomics — Brent Crude Oil (current price)", url: "https://tradingeconomics.com/commodity/brent-crude-oil" },
      { title: "OilPrice.com — Brent Crude Oil Futures Contracts (real-time futures price)", url: "https://oilprice.com/futures/brent/" },
      { title: "CNBC — Oil prices move higher as Iran threatens response to latest U.S. strikes (30 Jul 2026)", url: "https://www.cnbc.com/amp/2026/07/30/oil-prices-us-iran-war.html" },
      { title: "Bloomberg — Oil Holds Gain as Trump Vows to Hit Iran and US Stockpiles Slump (29-30 Jul 2026)", url: "https://www.bloomberg.com/news/articles/2026-07-29/latest-oil-market-news-and-analysis-for-july-30" },
      { title: "CNBC — Oil prices jump more than 4% after Trump threatens to bomb Iran and reimpose naval blockade (8 Jul 2026)", url: "https://www.cnbc.com/2026/07/08/oil-prices-brent-wti-iran-us-hormuz.html" },
      { title: "Wikipedia — 2026 Iran war ceasefire (timeline)", url: "https://en.wikipedia.org/wiki/2026_Iran_war_ceasefire" },
      { title: "Wikipedia — 2026 Strait of Hormuz crisis", url: "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis" },
      { title: "Databoks/Katadata — Iran continues to close the Strait of Hormuz, oil prices break $100/bbl (13 Mar 2026)", url: "https://databoks.katadata.co.id/en/datapublish/2026/03/13/iran-continues-to-close-the-strait-of-hormuz-oil-prices-break-us100-per-barrel" },
      { title: "Army Recognition — US and Israel Launch Operation Epic Fury Against Iran", url: "https://www.armyrecognition.com/news/army-news/2026/us-israel-launch-operation-epic-fury-against-iran-nuclear-program-and-missile-arsenal" },
      { title: "stockanalysis.com — XLE ETF overview (price, market cap, P/E, dividend yield)", url: "https://stockanalysis.com/etf/xle/" },
      { title: "Tickeron — XLE technical analysis (RSI, Aroon, moving averages)", url: "https://tickeron.com/ticker/XLE/" },
      { title: "FactSet Insight — S&P 500 Energy Sector Earnings Preview: Q2 2026 (quarterly YoY growth rates)", url: "https://insight.factset.com/sp-500-energy-sector-earnings-preview-q2-2026" },
      { title: "FactSet Insight — S&P 500 Earnings Season Update: July 17, 2026 (sector leaders, Healthcare sole decline)", url: "https://insight.factset.com/sp-500-earnings-season-update-july-17-2026" },
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed (re-verified: no +57%/-5% figures present)", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "Global News — EIA raises oil output forecast, says oversupply will weigh on prices in 2026", url: "https://globalnews.ca/news/11523165/eia-oil-price-forecast-oversupply-2026/" },
      { title: "OilPrice.com — Global Upstream Capex Set To Fall Again In 2026 Amid Low Oil Prices", url: "https://oilprice.com/Energy/Crude-Oil/Global-Upstream-Capex-Set-To-Fall-Again-In-2026-Amid-Low-Oil-Prices.html" },
    ],
    lastUpdated: "2026-07-31",
    author: "Atlas",
    trigger: "CIO/Bear brief update — war timeline + technical signal addendum to Energy entry (2026-07-30), plus re-verification of figures the brief itself flagged as unconfirmed",
  },
  {
    sector: "Gold / Precious Metals",
    slug: "gold-precious-metals",
    stance: "NEUTRAL",
    cyclePosition: "Late-cycle hedge / defensive rotation signal",
    headline: "Gold แทบ flat YTD หลัง round-trip +30%/-23% สุดขั้ว — S&P 500 ชนะ YTD ชัดเจนแม้ headline ทองดูน่าตื่นเต้นกว่า",
    thesis: "เรื่องเล่าที่ตลาดพูดถึงบ่อยคือ 'ทองชนะหุ้นปี 2026' แต่ตัวเลขจริงเมื่อดูทั้งปีบอกเรื่องตรงข้าม — gold ทำสถิติใหม่ $5,542-5,602/oz ปลายเดือนม.ค. 2026 (+30%+ ใน 4 สัปดาห์แรกของปี) แล้วพลิกกลับร่วงลงมาต่อเนื่องเหลือ ~$4,330-4,360/oz ปัจจุบัน (ลดลง ~22-23% จากพีค) ทำให้ YTD จริงๆ ของทองใกล้เคียง **flat (~+0.7-1%)** เทียบกับราคาเปิดปีที่ราว $4,313 (คำนวณย้อนจาก close $4,865.37 ม.ค.31 ซึ่ง +12.8% MoM) ในขณะที่ S&P 500 เดินหน้าทำสถิติปิดใหม่ต่อเนื่องด้วย **YTD +12.5%** (ณ 7 ส.ค. 2026) แบบไม่มีการ correction ลึกระหว่างทาง ภาพรวมคือหุ้นชนะทองขาดในปีนี้ทั้งที่ headline ข่าวทองดูน่าตื่นเต้นกว่ามาก (พาดหัวข่าวเน้นที่ spike/correction ระหว่างทางมากกว่าผลตอบแทนสุทธิ) — สาเหตุหลักของความผันผวนทองคือ real-rate/dollar swings รวมถึง geopolitical premium (Iran/Hormuz) ที่ผ่อนคลายลงหลัง de-escalation ต้นเดือนส.ค. ส่วนแรงหนุนเชิงโครงสร้างของทอง (central bank buying ต่อเนื่อง — 43% ของรัฐบาลวางแผนเพิ่ม reserve, de-dollarization trend) ยังไม่หายไปและอาจกลับมาเป็นแรงหนุนถ้า Fed หันมาลดดอกเบี้ยจริงตามที่ weak July jobs report เริ่มบ่งชี้ — แต่ ณ วันนี้ยังไม่ใช่จุดที่ทองราคาถูกเทียบ historical range จนน่าเปลี่ยนพอร์ตไปทางนั้น",
    keyPoints: [
      "Gold YTD 2026 ≈ flat (+0.7-1%) vs S&P 500 YTD +12.5% (7 ส.ค. 2026) — ตรงข้ามกับ narrative ตลาดที่มักพูดว่าทองชนะหุ้นปีนี้",
      "Gold spike +30%+ สู่สถิติใหม่ $5,542-5,602/oz (28-29 ม.ค. 2026) แล้ว correct ลงต่อเนื่อง -22-23% เหลือ ~$4,330-4,360/oz ปัจจุบัน — round-trip รุนแรงที่สุดในรอบปีของสินทรัพย์นี้",
      "Gold รีบาวด์ +7%+ ในสัปดาห์ล่าสุด (ต้นส.ค.) หลัง weak July jobs report (-23K payrolls) ดันตลาดคาด Fed dovish มากขึ้น — แต่ยังห่างจาก peak มาก",
      "แรงหนุนเชิงโครงสร้างยังอยู่: central bank buying ต่อเนื่อง (43% ของรัฐบาลวางแผนเพิ่ม gold reserve), de-dollarization trend, ความเสี่ยง real-rate ลดลงถ้า Fed cut จริง",
      "เชื่อมโยงพอร์ตโดยตรง: WPM (Wheaton Precious Metals, precious-metals streaming) วิเคราะห์เต็มแล้ว 2026-07-12 — NO DEPLOY (Conv 6.3<7.0, MOS -9.9%<15%) เพราะ Blended FV $99.20 ใช้ normalized gold $3,400-4,000 ไม่ใช่ spot record ตอนนั้น ($4,120) — ราคาทองปัจจุบัน ~$4,330-4,360 ยังไม่เข้า normalized zone แต่ trend ทิศทางถูกต้อง (correction จาก peak ต่อเนื่อง) ควรจับตาต่อว่าจะย่อเข้า $3,400-3,800 จริงหรือไม่",
    ],
    metrics: [
      { label: "S&P 500 YTD 2026", value: 12.5 },
      { label: "Gold YTD 2026 (est.)", value: 0.8 },
      { label: "Gold correction from Jan 2026 peak", value: -23 },
      { label: "Gold 1-week rally (early Aug)", value: 7 },
    ],
    relatedTickers: ["WPM"],
    sources: [
      { title: "Yahoo Finance — Gold prices today, Monday, August 10, 2026: Highest opening price since early June", url: "https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-monday-august-10-2026-highest-opening-price-since-early-june-123242269.html" },
      { title: "Yahoo Finance — Gold prices today, Friday, August 7, 2026: Gold prices continue to rise even after July jobs report misses", url: "https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-friday-august-7-2026-gold-prices-continue-to-rise-even-after-july-jobs-report-misses-122102132.html" },
      { title: "24/7 Wall St. — GLD Has Returned ~9% Year to Date While the S&P 500 Has Stalled (Apr 2026 snapshot, superseded by later data — kept for trend context)", url: "https://247wallst.com/investing/2026/04/23/gld-has-returned-9-year-to-date-while-the-sp-500-has-stalled-here-is-what-is-driving-gold-higher/" },
      { title: "StatMuse Money — Gold Price Per Ounce Jan 2026 Chart (Jan 31 close $4,865.37, +12.8% MoM)", url: "https://www.statmuse.com/money/ask/gold-price-per-ounce-jan-2026-chart" },
      { title: "GoldSilver.com — Gold Price Forecast 2026: What the Major Banks Are Predicting Now (record $5,542-5,602/oz late-Jan 2026, central bank buying context)", url: "https://goldsilver.com/industry-news/article/gold-price-forecast-2026-2027-key-predictions-from-top-analysts/" },
      { title: "StatMuse Money — S And P 500 Returns YTD 2026 (+12.5% as of 2026-08-07 close)", url: "https://www.statmuse.com/money/ask/s-and-p-500-returns-ytd-2026" },
    ],
    lastUpdated: "2026-08-10",
    author: "Atlas",
    trigger: "CIO ad-hoc request — gold vs S&P 500 comparison",
  },
];
