// ─── SECTOR VIEWS DATA ───────────────────────────────────────────
// Managed by Atlas · เขียนแบบ ad-hoc เมื่อทีมเกิด/ทบทวน view ระดับ sector เท่านั้น
// (ไม่ใช่ scheduled job แบบ /news-scan — ดู CLAUDE.md § Sector Views Protocol)
// กฎการเขียน: ห้ามแก้/ลบ entry เดิม — push entry ใหม่เข้า array เท่านั้น (append-only)
// เหตุผล: entry เก่าคือ audit trail ว่าทีมเคยคิดอะไรมาก่อน ณ วันไหน — การแก้ทับจะทำลายหลักฐานนั้น

const SECTOR_VIEWS_LAST_UPDATED = "2026-09-11 10:30";

const SECTOR_VIEWS = [
  {
    sector: "Energy",
    slug: "energy",
    stance: "NEGATIVE",
    cyclePosition: "Late-cycle",
    headline: "Late-cycle plateau เงินทุนใหม่เสี่ยงจ่ายที่จุดพีค — รอ de-escalation ก่อน",
    thesis: "พลังงานอยู่ช่วง late-cycle ที่ราคาถูกดันขึ้นด้วย geopolitical risk premium (Iran conflict, oil +5% แตะ $83+ วันเดียว) มากกว่า fundamental scarcity — สัญญาณชัดที่สุดคือ S&P 500 Energy earnings คาดโต +57% ปี 2026 แต่ consensus คาดหดตัว -5% ปี 2027 (pattern peak-then-decline ที่ตลาด price-in แล้ว) ประกอบกับ XLE พุ่ง +32-40% YTD ทิ้งห่าง S&P 500 และ Tech จนถูกมองว่า valuation ตึงเกินไปแล้ว ขณะที่ EIA/ING คาด oversupply 2.0-2.26 ล้านบาร์เรล/วันปี 2026 ซึ่งขัดแย้งกับราคาที่พุ่งอยู่ตอนนี้ — capex ยังมีวินัย (upstream ลดต่อเนื่องปีที่ 2) และ rig count ยังต่ำเทียบ shale-boom era จึงยังไม่ใช่ bubble-top แบบสุดขั้ว แต่การซื้อตอนนี้เท่ากับจ่ายที่ earnings peak + valuation แพง + geopolitical premium พร้อมกันทั้งสามอย่าง ซึ่งเสี่ยงเกินไปสำหรับ time horizon 3-5 ปีของกองทุน",
    keyPoints: [
      "S&P 500 Energy earnings: +57% (2026F) แล้วพลิกหด -5% (2027F) — สัญญาณ peak-then-decline จากตลาดเอง",
      "XLE +32-40% YTD 2026 (ทิ้งห่าง S&P 500 +8.8% และ Tech +23%) — valuation ตึงแล้ว, risk/reward tilted downside ตาม analyst",
      "EIA/ING คาด oversupply 2.0-2.26 ล้านบาร์เรล/วันปี 2026 — ราคาปัจจุบันขับเคลื่อนด้วย Iran conflict premium ไม่ใช่ scarcity จริง",
      "Upstream capex ลดต่อเนื่องปีที่ 2 (-2-3% YoY) + rig count ยังต่ำเทียบ shale-boom — ยังไม่ใช่ euphoria-style bubble top",
      "ถ้าจะพิจารณาจริง: integrated majors (XOM/CVX) หรือ midstream/pipeline (FCF นิ่งกว่า) ดีกว่า pure-play E&P ที่จะโดนแรงสุดถ้า cycle หัน",
    ],
    metrics: [
      { label: "Energy earnings growth 2026F", value: 57 },
      { label: "Energy earnings growth 2027F", value: -5 },
      { label: "XLE YTD return", value: 32 },
      { label: "S&P 500 YTD return", value: 8.8 },
    ],
    relatedTickers: [],
    sources: [
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "GuruFocus — Energy Sector Insights: Key Pivot Points for XLE", url: "https://www.gurufocus.com/news/8980339/energy-sector-insights-key-pivot-points-for-xle" },
      { title: "ING Think — Bearish oil outlook, but upside risks abound", url: "https://think.ing.com/articles/bearish-oil-outlook-but-clear-upside-risks/" },
      { title: "Bloomberg — OPEC Keeps 2026 Oil Supply, Demand Outlook Steady", url: "https://www.bloomberg.com/news/articles/2025-12-11/opec-data-point-to-balanced-global-oil-market-in-2026" },
      { title: "OilPrice — Global Upstream Capex Set To Fall Again In 2026 Amid Low Oil Prices", url: "https://oilprice.com/Energy/Crude-Oil/Global-Upstream-Capex-Set-To-Fall-Again-In-2026-Amid-Low-Oil-Prices.html" },
      { title: "Bloomberg — US Oil Rig Count Rises for 12th Week, Longest Streak Since 2022", url: "https://www.bloomberg.com/news/articles/2026-07-17/us-oil-rig-count-notches-longest-streak-without-drop-since-2022" },
      { title: "EIA — Weekly Petroleum Status Report (crude inventories)", url: "https://www.eia.gov/todayinenergy/detail.php?id=67868" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — energy sector cycle analysis",
  },
  {
    sector: "Software / AI",
    slug: "software-ai",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle",
    headline: "Secular growth ของจริง แต่ ROI-realization overhang กดราคาเป็นระลอก — selective ไม่ broad-avoid",
    thesis: "AI capex ของ hyperscaler ยังโตต่อเนื่องแรงมาก (4 รายใหญ่ guide รวม $670B ปี 2026, US Big Tech investment คาดโต +50% ทะลุ $600B, capex intensity ~23% ของ revenue สูงกว่ายุคก่อน ChatGPT กว่าเท่าตัว) แต่ประเด็นหลักที่ตลาดยังตัดสินใจไม่ได้คือช่องว่างระหว่างเงินที่ลงทุนกับ ROI ที่วัดผลได้จริง — Morgan Stanley เรียกช่วงนี้ว่า 'peak uncertainty' หลัง valuation กลุ่ม software/services ร่วงกลับมาใกล้ระดับที่เคยเห็นตอน disruption scare ครั้งก่อน สอดคล้องกับที่พอร์ตเราเจอเองปีนี้ (ADBE/CRM โดน downgrade เรื่อง capex-ROI overhang ก่อนจะเด้งกลับ, GOOGL stopDist เกือบ breach เพราะตลาด sell-the-news ทุกครั้งที่ capex guide ขึ้น แม้ Cloud growth จริงจะเร่งขึ้นต่อเนื่อง). ทีมยังไม่ avoid ทั้งกลุ่มเพราะ backlog/cloud growth เป็นหลักฐาน ROI ที่จับต้องได้จริงสำหรับผู้ชนะที่ชัดเจน (เช่น GOOGL Cloud +82%) แต่ยังไม่ commit เพิ่มทุนใหม่แบบไม่เลือกหน้า เพราะ mass productive deployment ในระดับ enterprise ยังไม่มาจริงตามที่ capex บอกไว้",
    keyPoints: [
      "4 hyperscaler ใหญ่ guide capex รวม $670B ปี 2026, US Big Tech +50% ทะลุ $600B, capex intensity ~23% ของ revenue",
      "Morgan Stanley: software/services valuation กลับมาใกล้ 'peak uncertainty' ระดับเดียวกับ disruption scare ครั้งก่อน",
      "ช่องว่าง capex-vs-ROI คือ bull/bear pivot หลักของกลุ่มทั้งปี 2026-2027 — mass enterprise deployment ยังไม่มาจริง",
      "หลักฐานเชิงประจักษ์จากพอร์ตเราเอง: ADBE/CRM/GOOGL ทั้งหมดโดน sell-the-news ซ้ำๆ ทุกครั้งที่มีข่าว capex แม้ fundamentals จริงจะแข็งแกร่งขึ้นต่อเนื่อง",
      "Technology sector Q2 2026 earnings +64.6% YoY (เร่งขึ้น) ยืนยันว่า demand ยังจริง ไม่ใช่แค่ hype — แต่ market ยัง discount ด้วย ROI doubt",
    ],
    metrics: [
      { label: "US Big Tech capex growth (YoY)", value: 50 },
      { label: "Capex intensity (% of revenue)", value: 23 },
      { label: "Technology sector Q2 2026 earnings growth", value: 64.6 },
    ],
    relatedTickers: ["ADBE", "NOW", "GOOGL", "CRM", "ADSK"],
    sources: [
      { title: "CNBC — AI boom: Big Tech capex now seen topping $1 trillion in 2027", url: "https://www.cnbc.com/2026/04/30/ai-boom-big-tech-capital-expenditures-now-seen-topping-1-trillion-in-2027-.html" },
      { title: "Goldman Sachs — Why AI Companies May Invest More than $500 Billion in 2026", url: "https://www.goldmansachs.com/insights/articles/why-ai-companies-may-invest-more-than-500-billion-in-2026" },
      { title: "PwC — Technology: US Deals 2026 midyear outlook", url: "https://www.pwc.com/us/en/industries/tmt/library/technology-deals-outlook.html" },
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — sector coverage expansion (portfolio is 6/8 positions Software/AI-adjacent)",
  },
  {
    sector: "Healthcare",
    slug: "healthcare",
    stance: "CAUTIOUS",
    cyclePosition: "Late-cycle / Defensive rotation",
    headline: "Valuation ถูก + rotation story น่าสนใจ แต่ earnings ยังหดตัวจริง และมี stock-specific risk ในพอร์ตเราเอง",
    thesis: "Sell-side หลายสำนัก (Janus Henderson, BlackRock iShares, Bloomberg) มองปี 2026 เป็นปีที่ healthcare 'กลับมา' ได้ — valuation ยังอยู่ใกล้จุดต่ำสุดในรอบ ~30 ปีจาก policy uncertainty ที่เริ่มคลี่คลาย (drug pricing reform ชัดเจนขึ้น, M&A เริ่มกลับมาคึกคัก) และเป็น sector defensive ที่มักได้ประโยชน์จาก rotation ช่วงปลายวัฏจักร แต่ข้อมูลจริงจาก Q2 2026 earnings season ขัดแย้งกับ narrative นี้ชัดเจน — FactSet รายงานว่า healthcare เป็น sector เดียวใน S&P 500 ที่ earnings หดตัว YoY ไตรมาสนี้ และหดตัวหนักที่สุดในบรรดาทุก sector ที่ -18.2% (แย่กว่าคาดการณ์เดิม -9.5% ก่อนหน้านี้) สาเหตุหลักมาจาก managed care/health insurer เจอ patient utilization สูงเกินคาด + ค่าใช้จ่ายยา GLP-1 พุ่ง ไม่ใช่แค่ sentiment ที่แย่ ทีมเจอสัญญาณ stock-specific คล้ายกันในพอร์ต/watchlist ของเราเอง: REGN เจอ securities class action lawsuit ใหม่ (Phase 3 melanoma setback), ZTS growth ชะลอเหลือ 2-5% พร้อม analyst PT ถูกหั่นต่อเนื่อง 2 รอบ, DXCM มีประวัติ crash -40% ในไตรมาสเดียวกันเมื่อ 2 ปีก่อน — ทำให้ยังไม่มั่นใจพอจะเรียกทั้ง sector ว่า positive แม้ valuation จะน่าสนใจ",
    keyPoints: [
      "Valuation healthcare ใกล้จุดต่ำสุดรอบ ~30 ปี จาก policy uncertainty ที่เริ่มคลี่คลาย (drug pricing reform, Medicare Advantage rate decision เม.ย.)",
      "Q2 2026: healthcare earnings -18.2% YoY (FactSet) — แย่ที่สุดในบรรดาทุก sector ของ S&P 500 และแย่กว่าคาดการณ์เดิม -9.5% ต้นเหตุจาก managed care/GLP-1 cost surge",
      "M&A activity เริ่มกลับมาคึกคักขึ้น เป็นสัญญาณบวกเชิง structural",
      "Stock-specific risk ในพอร์ต/watchlist เราเอง: REGN lawsuit ใหม่, ZTS growth deceleration + PT cuts 2 รอบ, DXCM มี crash pattern -40% ประวัติศาสตร์ก่อน earnings",
      "สรุป: เป็น sector ที่ 'น่าดูใกล้ชิด' ไม่ใช่ 'รีบเพิ่มทุน' — รอดู Q3 earnings ว่า decline เป็น trough จริงหรือแค่เริ่มต้น",
    ],
    metrics: [
      { label: "Healthcare Q2 2026 earnings growth", value: -18.2 },
      { label: "S&P 500 overall Q2 2026 earnings growth", value: 24.5 },
    ],
    relatedTickers: ["REGN", "DXCM", "ZTS", "PODD"],
    sources: [
      { title: "Bloomberg — Healthcare Looks Ready to Star in Rotation Trade", url: "https://www.bloomberg.com/news/articles/2026-07-13/healthcare-looks-ready-to-star-in-rotation-trade-taking-stock" },
      { title: "Janus Henderson — Why healthcare stocks could excel in 2026", url: "https://www.janushenderson.com/article/why-healthcare-stocks-could-excel-in-2026/" },
      { title: "BlackRock iShares — Healthcare making a comeback?", url: "https://www.blackrock.com/au/insights/ishares/2026-comeback-year-for-healthcare" },
      { title: "Forbes — S&P 500 Earnings Outlook (healthcare sole YoY earnings decline)", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "ETF Trends — Q2 Earnings Preview: Tech & Energy Drive Growth Amid Healthcare Headwinds", url: "https://www.etftrends.com/sector-investing-content-hub/q2-earnings-preview-tech-energy-drive-growth-amid-healthcare-headwinds/" },
    ],
    lastUpdated: "2026-07-30",
    author: "Atlas",
    trigger: "CIO ad-hoc request — sector coverage expansion (portfolio holds REGN + DXCM/ZTS/PODD watchlist)",
  },
  {
    sector: "Energy",
    slug: "energy",
    stance: "NEGATIVE",
    cyclePosition: "Late-cycle",
    headline: "War premium ยังไม่นิ่ง — Brent ดีดกลับ $89-90 ปลาย ก.ค. (ไม่ใช่ $76 ตามที่ brief เข้าใจ) เทคนิคเริ่มอ่อนตัว ยืนยัน 'รอ' ไม่ใช่ 'เข้า'",
    thesis: "อัปเดตต่อยอด entry Energy เดิม (30 ก.ค. 2026, NEGATIVE) จาก brief ของ CIO/Bear ที่ขอให้ verify war timeline + technical signals + ตัวเลขที่ยังไม่ยืนยัน — ทีม WebFetch หลายแหล่ง (TradingEconomics, OilPrice.com futures, CNBC, Bloomberg) พบว่า ณ 29-30 ก.ค. 2026 Brent อยู่ที่ราว $89-90/bbl ไม่ใช่ $76-77 ตามที่ brief อ้าง เพราะเกิดการยกระดับความรุนแรงรอบใหม่ (สหรัฐฯ โจมตี Iran คืนวันที่ 29 ก.ค. ตอบโต้การโจมตีฐานทัพสหรัฐฯ, Iran ขู่ตอบโต้เพิ่ม, กลุ่มติดอาวุธหนุน Iran ยิงโดรนใส่โรงกลั่นซาอุฯ ต่อเนื่อง 2 วัน) หลัง ceasefire เดิมพังไปแล้วตั้งแต่ 8 ก.ค. timeline สงครามที่ verify แล้วก็คลาดเคลื่อนจาก brief หลายจุด: peak ราคาแรกอยู่ที่ $116.29/bbl วันที่ 9 มี.ค. (ไม่ใช่ช่วง 11-24 มี.ค.), ceasefire จริงครั้งแรกเกิด 7-8 เม.ย. ไม่ใช่ 23-31 มี.ค. ตามที่ brief อ้าง (มีแต่การเจรจา/บล็อกท่าเรือระหว่างนั้น ไม่มี ceasefire ในมี.ค.) จากนั้นขยายไม่มีกำหนด 21 เม.ย., เจรจา Islamabad ล้มเหลวกลาง เม.ย., เซ็น MOU 60 วันรอบใหม่ 17 มิ.ย. ก่อนพังอีกครั้ง 8 ก.ค. และ escalate ต่อเนื่องถึงปลาย ก.ค. — ทั้งหมดนี้ยืนยันว่าความเสี่ยงเป็น dual-direction จริงตามที่ brief เตือน สงครามยังไม่จบ ราคาสวิงได้ทั้งพุ่งแรงกว่านี้ถ้า Hormuz ปิดอีกรอบ และร่วงแรงถ้า de-escalate จริงจัง ไม่ใช่ downside scenario เดียวที่เคยเน้น ด้านเทคนิคของ XLE เริ่มส่งสัญญาณอ่อนตัวสอดคล้องกับความเสี่ยงนี้: Aroon เข้าสู่ downtrend ตั้งแต่ 13 ก.ค., RSI(14) เคยพุ่งถึง 85 (severely overbought) ก่อนหลุดจากโซน overbought เมื่อ 27 ก.ค. แม้จะมี bullish MA crossover (10dma ตัดขึ้นเหนือ 50dma เมื่อ 20 ก.ค.) แทรกอยู่ทำให้ signal ยังไม่ชี้ทางเดียวขาด แต่ momentum โดยรวมเริ่มเสีย ด้าน valuation หลัง verify จริงผ่าน stockanalysis.com: XLE ราคา $58.59 market cap ~$39.5B P/E 20.94 div yield 2.59% (ตรงกับตัวเลขที่ brief อ้างเกือบสนิท) YTD return อยู่ราว 30-35% แล้วแต่แหล่ง/วันวัด ส่วนคำถามที่ brief สงสัยเองว่า Tech comeback อาจทำให้ gap แคบลง ทีมตรวจแล้วพบว่าถูกทิศทางจริง — XLK ปีนี้ให้ผลตอบแทนประมาณ 33% ใกล้เคียง XLE มาก ต่างจาก entry เดิมที่ gap อยู่ราว 9-17 จุด แปลว่า gap แคบลงจริง แต่ตัวเลข quarter-specific ที่ brief อ้าง (XLK Q2 +43% large cap, Energy large cap -13%) หาแหล่งยืนยันไม่เจอเลยในทุกแหล่งที่ค้น จึงต้องระบุว่า unverified สำหรับตัวเลขนั้นโดยเฉพาะ ประเด็นที่สำคัญที่สุดคือตัวเลข earnings เดิม: +57% (2026F) / -5% (2027F) ที่ entry เก่าอ้างอิง Forbes — ทีม re-fetch บทความ Forbes ตรงๆ แล้วพบว่าบทความไม่มีตัวเลขนี้เลย มีแค่ข้อความว่า Energy นำ Q2 ตามด้วย Tech โดยไม่ระบุเปอร์เซ็นต์ และไม่มี forecast ปี 2027 เลย ตัวเลขจริงที่ verify ได้จาก FactSet คือ Energy earnings growth YoY: Q2 2026 +122.9% (สูงกว่าที่เคยอ้างมาก) ลดหลั่นเหลือ Q3 2026 +75.6%, Q4 2026 +69.5%, Q1 2027 +49.6% แล้วพลิกลบ Q2 2027 -26.3% — ยืนยัน pattern peak-then-decline เดียวกับ thesis เดิม เพียงแต่ magnitude ต่างจากที่เคยอ้างไว้มาก ทีมอื่นควรใช้ตัวเลขชุดนี้แทนตัวเลขเดิม ส่วน EIA oversupply 2.0-2.26 mb/d และ upstream capex -2 ถึง -3% YoY ที่ brief ขอให้ verify ทั้งสองผ่านตรงตามอ้าง (EIA คาด glut 2.2 mb/d ปี 2026, OilPrice.com ยืนยัน capex ลดต่อเนื่องปีที่ 2) สรุป: stance ยังคง NEGATIVE เหมือนเดิม แต่ต้อง update ว่าความเสี่ยงตอนนี้กำลัง escalate ไปในทิศ 'ราคาสูงกว่าที่คิด' ไม่ใช่ de-escalate ตามที่ brief เข้าใจตอนแรก — เข้าซื้อตอนนี้เสี่ยงจ่ายที่ war-premium peak ซ้อนกับ valuation ตึงและ momentum กำลังเสียพร้อมกันสามชั้น",
    keyPoints: [
      "Brent ปัจจุบัน (29-30 ก.ค. 2026) อยู่ที่ราว $89-90/bbl หลังยกระดับรุนแรงรอบใหม่ (สหรัฐฯ โจมตี Iran, Iran ขู่ตอบโต้, โดรนโจมตีโรงกลั่นซาอุฯ) — ไม่ใช่ $76-77 ตามที่ brief เข้าใจตอนแรก คลาดเคลื่อนจริง",
      "Timeline สงคราม verify แล้ว: เริ่ม 28 ก.พ. (Operation Epic Fury/Roaring Lion) → peak $116.29 วันที่ 9 มี.ค. → ceasefire จริงครั้งแรก 7-8 เม.ย. (ไม่ใช่มี.ค. ตามที่ brief อ้าง) → ขยายไม่มีกำหนด 21 เม.ย. → MOU รอบใหม่ 17 มิ.ย. → พังอีกครั้ง 8 ก.ค. → escalate ต่อเนื่องถึง 29-30 ก.ค.",
      "เทคนิคเริ่มอ่อนตัว: Aroon downtrend ตั้งแต่ 13 ก.ค., RSI(14) เคยแตะ 85 ก่อนหลุด overbought 27 ก.ค. — แม้มี bullish MA crossover แทรก signal ยังไม่ชี้ทางเดียวขาด",
      "ตัวเลข earnings เดิม +57%/-5% ที่อ้าง Forbes ไม่มีอยู่จริงในบทความ — ตัวเลข FactSet ที่ verify ได้คือ Q2 2026 +122.9% ลดหลั่นจนพลิกลบ -26.3% ใน Q2 2027 (peak-then-decline ยืนยัน แต่ magnitude ต่างจากเดิมมาก)",
      "EIA oversupply 2.2 mb/d และ upstream capex -2 ถึง -3% YoY verify ผ่านตรงตามอ้าง — gap XLE vs Tech แคบลงจริง (XLE YTD ~30-35% vs XLK ~33%) แต่ตัวเลข quarter-specific +43%/-13% หาแหล่งยืนยันไม่เจอ (unverified)",
    ],
    metrics: [
      { label: "Brent crude ปัจจุบัน (29-30 ก.ค. 2026, USD/bbl)", value: 89 },
      { label: "Brent crude พีคสงคราม (9 มี.ค. 2026, USD/bbl)", value: 116 },
      { label: "S&P 500 Energy earnings growth Q2 2026 (YoY %)", value: 122.9 },
      { label: "S&P 500 Energy earnings growth Q2 2027F (YoY %)", value: -26.3 },
    ],
    relatedTickers: ["XLE", "XOM", "CVX"],
    sources: [
      { title: "TradingEconomics — Brent Crude Oil (current price)", url: "https://tradingeconomics.com/commodity/brent-crude-oil" },
      { title: "OilPrice.com — Brent Crude Oil Futures Contracts (real-time futures price)", url: "https://oilprice.com/futures/brent/" },
      { title: "CNBC — Oil prices move higher as Iran threatens response to latest U.S. strikes (30 Jul 2026)", url: "https://www.cnbc.com/amp/2026/07/30/oil-prices-us-iran-war.html" },
      { title: "Bloomberg — Oil Holds Gain as Trump Vows to Hit Iran and US Stockpiles Slump (29-30 Jul 2026)", url: "https://www.bloomberg.com/news/articles/2026-07-29/latest-oil-market-news-and-analysis-for-july-30" },
      { title: "CNBC — Oil prices jump more than 4% after Trump threatens to bomb Iran and reimpose naval blockade (8 Jul 2026)", url: "https://www.cnbc.com/2026/07/08/oil-prices-brent-wti-iran-us-hormuz.html" },
      { title: "Wikipedia — 2026 Iran war ceasefire (timeline)", url: "https://en.wikipedia.org/wiki/2026_Iran_war_ceasefire" },
      { title: "Wikipedia — 2026 Strait of Hormuz crisis", url: "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis" },
      { title: "Databoks/Katadata — Iran continues to close the Strait of Hormuz, oil prices break $100/bbl (13 Mar 2026)", url: "https://databoks.katadata.co.id/en/datapublish/2026/03/13/iran-continues-to-close-the-strait-of-hormuz-oil-prices-break-us100-per-barrel" },
      { title: "Army Recognition — US and Israel Launch Operation Epic Fury Against Iran", url: "https://www.armyrecognition.com/news/army-news/2026/us-israel-launch-operation-epic-fury-against-iran-nuclear-program-and-missile-arsenal" },
      { title: "stockanalysis.com — XLE ETF overview (price, market cap, P/E, dividend yield)", url: "https://stockanalysis.com/etf/xle/" },
      { title: "Tickeron — XLE technical analysis (RSI, Aroon, moving averages)", url: "https://tickeron.com/ticker/XLE/" },
      { title: "FactSet Insight — S&P 500 Energy Sector Earnings Preview: Q2 2026 (quarterly YoY growth rates)", url: "https://insight.factset.com/sp-500-energy-sector-earnings-preview-q2-2026" },
      { title: "FactSet Insight — S&P 500 Earnings Season Update: July 17, 2026 (sector leaders, Healthcare sole decline)", url: "https://insight.factset.com/sp-500-earnings-season-update-july-17-2026" },
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed (re-verified: no +57%/-5% figures present)", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
      { title: "Global News — EIA raises oil output forecast, says oversupply will weigh on prices in 2026", url: "https://globalnews.ca/news/11523165/eia-oil-price-forecast-oversupply-2026/" },
      { title: "OilPrice.com — Global Upstream Capex Set To Fall Again In 2026 Amid Low Oil Prices", url: "https://oilprice.com/Energy/Crude-Oil/Global-Upstream-Capex-Set-To-Fall-Again-In-2026-Amid-Low-Oil-Prices.html" },
    ],
    lastUpdated: "2026-07-31",
    author: "Atlas",
    trigger: "CIO/Bear brief update — war timeline + technical signal addendum to Energy entry (2026-07-30), plus re-verification of figures the brief itself flagged as unconfirmed",
  },
  {
    sector: "Gold / Precious Metals",
    slug: "gold-precious-metals",
    stance: "NEUTRAL",
    cyclePosition: "Late-cycle hedge / defensive rotation signal",
    headline: "Gold แทบ flat YTD หลัง round-trip +30%/-23% สุดขั้ว — S&P 500 ชนะ YTD ชัดเจนแม้ headline ทองดูน่าตื่นเต้นกว่า",
    thesis: "เรื่องเล่าที่ตลาดพูดถึงบ่อยคือ 'ทองชนะหุ้นปี 2026' แต่ตัวเลขจริงเมื่อดูทั้งปีบอกเรื่องตรงข้าม — gold ทำสถิติใหม่ $5,542-5,602/oz ปลายเดือนม.ค. 2026 (+30%+ ใน 4 สัปดาห์แรกของปี) แล้วพลิกกลับร่วงลงมาต่อเนื่องเหลือ ~$4,330-4,360/oz ปัจจุบัน (ลดลง ~22-23% จากพีค) ทำให้ YTD จริงๆ ของทองใกล้เคียง **flat (~+0.7-1%)** เทียบกับราคาเปิดปีที่ราว $4,313 (คำนวณย้อนจาก close $4,865.37 ม.ค.31 ซึ่ง +12.8% MoM) ในขณะที่ S&P 500 เดินหน้าทำสถิติปิดใหม่ต่อเนื่องด้วย **YTD +12.5%** (ณ 7 ส.ค. 2026) แบบไม่มีการ correction ลึกระหว่างทาง ภาพรวมคือหุ้นชนะทองขาดในปีนี้ทั้งที่ headline ข่าวทองดูน่าตื่นเต้นกว่ามาก (พาดหัวข่าวเน้นที่ spike/correction ระหว่างทางมากกว่าผลตอบแทนสุทธิ) — สาเหตุหลักของความผันผวนทองคือ real-rate/dollar swings รวมถึง geopolitical premium (Iran/Hormuz) ที่ผ่อนคลายลงหลัง de-escalation ต้นเดือนส.ค. ส่วนแรงหนุนเชิงโครงสร้างของทอง (central bank buying ต่อเนื่อง — 43% ของรัฐบาลวางแผนเพิ่ม reserve, de-dollarization trend) ยังไม่หายไปและอาจกลับมาเป็นแรงหนุนถ้า Fed หันมาลดดอกเบี้ยจริงตามที่ weak July jobs report เริ่มบ่งชี้ — แต่ ณ วันนี้ยังไม่ใช่จุดที่ทองราคาถูกเทียบ historical range จนน่าเปลี่ยนพอร์ตไปทางนั้น",
    keyPoints: [
      "Gold YTD 2026 ≈ flat (+0.7-1%) vs S&P 500 YTD +12.5% (7 ส.ค. 2026) — ตรงข้ามกับ narrative ตลาดที่มักพูดว่าทองชนะหุ้นปีนี้",
      "Gold spike +30%+ สู่สถิติใหม่ $5,542-5,602/oz (28-29 ม.ค. 2026) แล้ว correct ลงต่อเนื่อง -22-23% เหลือ ~$4,330-4,360/oz ปัจจุบัน — round-trip รุนแรงที่สุดในรอบปีของสินทรัพย์นี้",
      "Gold รีบาวด์ +7%+ ในสัปดาห์ล่าสุด (ต้นส.ค.) หลัง weak July jobs report (-23K payrolls) ดันตลาดคาด Fed dovish มากขึ้น — แต่ยังห่างจาก peak มาก",
      "แรงหนุนเชิงโครงสร้างยังอยู่: central bank buying ต่อเนื่อง (43% ของรัฐบาลวางแผนเพิ่ม gold reserve), de-dollarization trend, ความเสี่ยง real-rate ลดลงถ้า Fed cut จริง",
      "เชื่อมโยงพอร์ตโดยตรง: WPM (Wheaton Precious Metals, precious-metals streaming) วิเคราะห์เต็มแล้ว 2026-07-12 — NO DEPLOY (Conv 6.3<7.0, MOS -9.9%<15%) เพราะ Blended FV $99.20 ใช้ normalized gold $3,400-4,000 ไม่ใช่ spot record ตอนนั้น ($4,120) — ราคาทองปัจจุบัน ~$4,330-4,360 ยังไม่เข้า normalized zone แต่ trend ทิศทางถูกต้อง (correction จาก peak ต่อเนื่อง) ควรจับตาต่อว่าจะย่อเข้า $3,400-3,800 จริงหรือไม่",
    ],
    metrics: [
      { label: "S&P 500 YTD 2026", value: 12.5 },
      { label: "Gold YTD 2026 (est.)", value: 0.8 },
      { label: "Gold correction from Jan 2026 peak", value: -23 },
      { label: "Gold 1-week rally (early Aug)", value: 7 },
    ],
    relatedTickers: ["WPM"],
    sources: [
      { title: "Yahoo Finance — Gold prices today, Monday, August 10, 2026: Highest opening price since early June", url: "https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-monday-august-10-2026-highest-opening-price-since-early-june-123242269.html" },
      { title: "Yahoo Finance — Gold prices today, Friday, August 7, 2026: Gold prices continue to rise even after July jobs report misses", url: "https://finance.yahoo.com/personal-finance/investing/article/gold-prices-today-friday-august-7-2026-gold-prices-continue-to-rise-even-after-july-jobs-report-misses-122102132.html" },
      { title: "24/7 Wall St. — GLD Has Returned ~9% Year to Date While the S&P 500 Has Stalled (Apr 2026 snapshot, superseded by later data — kept for trend context)", url: "https://247wallst.com/investing/2026/04/23/gld-has-returned-9-year-to-date-while-the-sp-500-has-stalled-here-is-what-is-driving-gold-higher/" },
      { title: "StatMuse Money — Gold Price Per Ounce Jan 2026 Chart (Jan 31 close $4,865.37, +12.8% MoM)", url: "https://www.statmuse.com/money/ask/gold-price-per-ounce-jan-2026-chart" },
      { title: "GoldSilver.com — Gold Price Forecast 2026: What the Major Banks Are Predicting Now (record $5,542-5,602/oz late-Jan 2026, central bank buying context)", url: "https://goldsilver.com/industry-news/article/gold-price-forecast-2026-2027-key-predictions-from-top-analysts/" },
      { title: "StatMuse Money — S And P 500 Returns YTD 2026 (+12.5% as of 2026-08-07 close)", url: "https://www.statmuse.com/money/ask/s-and-p-500-returns-ytd-2026" },
    ],
    lastUpdated: "2026-08-10",
    author: "Atlas",
    trigger: "CIO ad-hoc request — gold vs S&P 500 comparison",
  },
  {
    sector: "Stablecoin / Crypto-Fintech Infrastructure",
    slug: "stablecoin-crypto-fintech",
    stance: "CAUTIOUS",
    cyclePosition: "Rate-cycle sensitive / early commoditization phase",
    headline: "Stablecoin adoption ของจริง แต่ issuer economics เข้าสู่ commoditization + โดน Fed cuts กด float income พร้อมกัน — selective ไม่ broad-buy",
    thesis: "การวิเคราะห์ CRCL (Circle, 2026-08-28) เปิดเผยมุมมองระดับ sector ที่กว้างกว่าตัวหุ้น — stablecoin/crypto-fintech infrastructure กำลังเจอ 2 แรงบีบเชิงโครงสร้างพร้อมกัน (1) **Rate-cycle headwind:** ผู้ออก stablecoin หารายได้หลักจาก reserve income (ดอกเบี้ยบน USD reserve assets) — Circle ~95% ของ revenue เป็น float income และ reserve income Q2 2026 โตแค่ +5% YoY ทั้งที่ USDC average circulation โต +25% เพราะ Reserve Return Rate ลด -66bps YoY จาก Fed cuts ในภาวะ RISK-ON/easing regime ที่ตลาดมองว่าดีต่อ growth equity ทั่วไป กลุ่มนี้กลับสวนทาง (2) **Commoditization ของ distribution economics:** GENIUS Act (กม. stablecoin สหรัฐฯ 2025) เปิดทางผู้เล่นใหม่จำนวนมาก — PayPal PYUSD (ขยาย 70 ตลาด), Open USD consortium 140+ บริษัท (Visa/Mastercard/Stripe/Coinbase/Shopify/BlackRock) ที่ประกาศ 30 มิ.ย. 2026 คืน reserve income ส่วนใหญ่ให้พันธมิตร (CRCL ร่วง 8% วันนั้น) — และที่สำคัญคือ Coinbase ซึ่งเป็น distribution partner หลักของ Circle กลับหนุนคู่แข่ง stablecoin tech เป็น commodity ไปแล้ว ผู้ชนะระยะยาวคือใครก็ตามที่คุม distribution + volume ไม่ใช่ผู้ที่มี tech ดีที่สุด — usage เริ่มแยกจาก supply (USDC ครอง ~70% ของ adjusted transaction volume H1 2026 แต่ supply share แค่ ~23-24% เทียบ Tether ~59%) ทีมยังไม่ avoid ทั้งกลุ่มเพราะ secular adoption จริง (onchain transaction volume +151% YoY, regulatory clarity จาก GENIUS Act, TAM ขยาย) แต่ CAUTIOUS ต่อ pure issuer ที่ earnings ผูก inverse กับ rate cycle และ selective เฉพาะ platform ที่มี volume/distribution moat + margin structure ที่ทน (เช่น HOOD op margin 46% vs CRCL/COIN ~7%)",
    keyPoints: [
      "Reserve-income model = inverse rate sensitivity: Circle reserve income Q2 2026 +5% YoY ทั้งที่ circulation +25% — Reserve Return Rate -66bps YoY จาก Fed cuts",
      "Fed easing regime (RISK-ON 4/4) เป็น structural revenue headwind ต่อ stablecoin issuer — สวนทางกับ growth equity ทั่วไป",
      "Commoditization: GENIUS Act + Open USD consortium (Visa/MC/Stripe/Coinbase/BlackRock, 30 มิ.ย. 2026) + PayPal PYUSD กด distribution economics ของ incumbent issuer",
      "Coinbase = distribution partner หลักของ Circle แต่หนุน Open USD คู่แข่ง — conflict เชิงโครงสร้าง, FY2025 gross margin ของ Circle ร่วงเหลือ 8.67% จาก distribution cost",
      "Usage แยกจาก supply: USDC ~70% ของ adjusted transaction volume H1 2026 vs supply share ~23-24% (Tether ~59%) — onchain volume ทั้งกลุ่ม +151% YoY = adoption จริง",
      "Selective: platform ที่มี volume/distribution moat + margin ที่ทน (HOOD op margin 46%) น่าสนใจกว่า pure issuer (CRCL/COIN op margin ~7%)",
    ],
    metrics: [
      { label: "Circle USDC circulation growth YoY (Q2 2026)", value: 19 },
      { label: "Circle reserve income growth YoY (Q2 2026)", value: 5 },
      { label: "Reserve Return Rate change YoY (bps)", value: -66 },
      { label: "Industry onchain transaction volume growth YoY (Q2 2026)", value: 151 },
    ],
    relatedTickers: ["CRCL", "COIN", "PYPL", "HOOD"],
    sources: [
      { title: "Circle — Circle Reports Second Quarter 2026 Results", url: "https://www.circle.com/pressroom/circle-reports-second-quarter-2026-results" },
      { title: "CoinDesk — Circle Slides 8% as Stripe, Coinbase and BlackRock Back Rival Stablecoin Network", url: "https://www.coindesk.com/business/2026/06/30/circle-slides-8-as-stripe-coinbase-and-blackrock-back-rival-stablecoin-network" },
      { title: "CoinDesk — Circle's USDC Is Leaving Tether Behind in the Stablecoin Volume Race", url: "https://www.coindesk.com/business/2026/07/06/circle-s-usdc-is-leaving-tether-behind-in-the-stablecoin-volume-race" },
      { title: "CoinDesk — Circle Stock Plunges 18% as a New Draft of the CLARITY Act Threatens Stablecoin Rewards", url: "https://www.coindesk.com/markets/2026/03/24/circle-stock-plunges-18-as-a-new-draft-of-the-clarity-act-threatens-stablecoin-rewards" },
      { title: "The Motley Fool — Which Stablecoins Are the Largest and Most Popular in 2026?", url: "https://www.fool.com/research/largest-stablecoins/" },
      { title: "CoinLaw — Stablecoin Market Cap Statistics 2026: Issuer Share and Growth", url: "https://coinlaw.io/stablecoin-market-cap-statistics/" },
    ],
    lastUpdated: "2026-08-28",
    author: "Atlas",
    trigger: "Byproduct of CRCL Phase 1 Macro Brief — reveals sector-level view on stablecoin issuer economics (rate-cycle + commoditization), applies beyond CRCL to COIN/PYPL/HOOD",
  },
  {
    sector: "Semiconductors — Analog & Mixed-Signal",
    slug: "semiconductors-analog",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle",
    headline: "Analog recovery ของจริงและกว้าง — แต่ตลาดจ่ายราคา cycle-peak multiple ก่อน 2027 comp wall + Fed hawkish กลับมา",
    thesis: "การวิเคราะห์ ADI (2026-08-29) เปิดเผยมุมมองระดับ sector — analog semiconductor (ADI, TXN, NXPI, MCHP, ON) กำลังฟื้นจาก downturn ที่ลึกและยาว (ADI revenue trough FY2024 -23.4% YoY) และการฟื้นตอนนี้ 'กว้างมาก' ตามที่ management ทั้ง ADI และ TXN บอกตรงกัน — โตทุก end-market พร้อมกัน (industrial restock, auto content, และที่ใหม่คือ data-center/AI pull บน analog+power content) BofA คาด diversified semiconductor sales ของ top suppliers เร่งขึ้นเป็น +19% ปี 2026 จากแค่ +1% ปี 2025 (CAGR ~12% ถึง 2028) ADI report record bookings ทั่วทุก B2B market และ Q3 FY2026 เป็น quarter แรกที่ทะลุ $4B (+40% YoY, Comms +84% YoY) โครงสร้างของ analog ยังน่าสนใจในเชิงคุณภาพ: product lifecycle 10-20 ปี, gross margin 65-72%, fab-lite (capex ~4% ของ revenue), FCF machine, pricing power, wide moat จาก consolidation (ADI+Linear+Maxim, TXN scale) — ต่างจาก memory (MU) ที่เป็น commodity price-taker อย่างสิ้นเชิง **แต่ทีมยัง CAUTIOUS ไม่ POSITIVE** เพราะ 3 เหตุผล: (1) valuation — ADI เทรด ~43x trailing P/E, EV/Revenue ~12x บน revenue ที่ inflate จาก trough comp (TTM revenue สูงกว่า prior-peak FY2023 แล้ว) ตลาดจ่ายราคา perfection ที่ cyclical high multiple (2) 2027 comp wall + double-order risk — +40% YoY และ Comms +84% ไม่ใช่ run-rate ที่ยั่งยืน ถ้าการฟื้นวิ่งนำ end-demand จริง (channel restock > sell-through) 2027 จะ decelerate แรง ซึ่งเป็น failure mode คลาสสิกของ analog cycle (3) Fed hawkish shift (Warsh Jackson Hole, Sept hike ~50/50) กด high-multiple semi + ชะลอ industrial capex ที่เป็น ~50% ของ mix พร้อมกัน — selective เฉพาะชื่อที่มี real margin of safety บน normalized (ไม่ใช่ peak) earnings เท่านั้น",
    keyPoints: [
      "Recovery กว้างและ broad-based — ADI + TXN management บอกตรงกันว่า demand 'อยู่ทุกที่'; BofA คาด diversified semi sales +19% 2026F vs +1% 2025 (CAGR ~12% ถึง 2028)",
      "Quality cycle ต่างจาก memory: product lifecycle 10-20 ปี, GM 65-72%, fab-lite capex ~4% ของ rev, FCF machine, pricing power, moat จาก consolidation (ADI/Linear/Maxim, TXN scale)",
      "Analog lag memory/logic ในการฟื้น — ADI trough FY2024 (-23%), ตอนนี้ mid-cycle recovery ไม่ใช่ early; pockets ร้อน (Comms +84% YoY = AI data-center content step-up, เป็น secular overlay จริง)",
      "Valuation overhang: ADI ~43x trailing P/E / EV/Rev ~12x บน revenue ที่ inflate จาก trough comp (TTM > prior-peak FY2023) — ตลาดจ่าย cycle-peak multiple",
      "2027 comp wall + double-order risk = failure mode คลาสสิกของ analog cycle; Fed hawkish (Sept hike ~50/50) กด multiple + ชะลอ industrial capex (~50% ของ ADI mix) พร้อมกัน",
      "Peer cycle position กระจายมาก: ON ยัง -3% YoY (ยัง downturn), NXPI +9%, MCHP +21%, ADI +34% — ตำแหน่ง cycle ไม่เท่ากัน, selective by name",
    ],
    metrics: [
      { label: "Diversified semi sales growth 2026F (BofA)", value: 19 },
      { label: "Diversified semi sales growth 2025 (BofA)", value: 1 },
      { label: "ADI Q3 FY2026 revenue growth YoY", value: 40 },
      { label: "ADI Industrial segment Q3 growth YoY", value: 53 },
    ],
    relatedTickers: ["ADI", "TXN", "NXPI", "MCHP", "ON"],
    sources: [
      { title: "Investing.com — Top analog semiconductor stocks as sector recovery gains momentum (BofA +19% 2026F, 12% CAGR to 2028)", url: "https://www.investing.com/news/stock-market-news/top-analog-semiconductor-stocks-as-sector-recovery-gains-momentum-93CH-4794264" },
      { title: "Investing.com — Analog Devices Surges 9% on Record Orders: 5 Chip Stocks Riding the Analog Recovery", url: "https://www.investing.com/analysis/analog-devices-surges-9-on-record-orders5-chip-stocks-riding-the-analog-recovery-200675272" },
      { title: "Analog Devices — Reports Record Fiscal Third Quarter 2026 (first $4B quarter, end-market mix, +40% YoY)", url: "https://investor.analog.com/news-releases/news-release-details/analog-devices-reports-record-fiscal-third-quarter-2026/" },
      { title: "CNBC — S&P 500 falls to start the week, dragged down by a sell-off in chip stocks (2026-08-23)", url: "https://www.cnbc.com/2026/08/23/stock-market-today-live-updates.html" },
      { title: "CNBC — September Fed decision now a coin flip as rate hike odds increase post Warsh (2026-08-28)", url: "https://www.cnbc.com/2026/08/28/-september-fed-decision-now-a-coin-flip-as-rate-hike-odds-increase.html" },
    ],
    lastUpdated: "2026-08-29",
    author: "Atlas",
    trigger: "Byproduct of ADI Phase 1 Macro Brief — reveals sector-level view on the analog semiconductor cycle (mid-cycle recovery vs cycle-peak valuation + Fed hawkish), applies beyond ADI to TXN/NXPI/MCHP/ON",
  },
  {
    sector: "LatAm E-commerce & Fintech",
    slug: "latam-ecommerce-fintech",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle",
    headline: "Structural winner ในภูมิภาคที่ valuation ถูกสุดใน 2 ทศวรรษ — แต่กลุ่มอยู่ใน margin-compression investment phase + Fed hawkish/strong-dollar เป็น EM headwind เฉพาะหน้า",
    thesis: "การวิเคราะห์ MELI (2026-08-29) เปิดเผยมุมมองระดับ sector ที่กว้างกว่าตัวหุ้น — LatAm digital commerce + fintech (MELI, SE/Shopee ในเชิง analog, NU, StoneCo, dLocal) กำลังเจอ 3 แรงพร้อมกัน (1) **Structural tailwind:** LatAm rate-cutting cycle เพิ่งเริ่ม (Brazil Selic ลดรอบที่ 4 ติดเหลือ 14.00% เมื่อ 5 ส.ค., Focus คาดจบปี 13.75%; Argentina disinflation จาก 211% YoY สู่ ~33% ใน 18 เดือน + primary surplus + Fitch upgrade CCC+→B-) = consumer credit demand ฟื้น + credit-loss ต่ำลง + local multiple re-rate; e-commerce penetration ยังต่ำ (~12% CAGR); Mercado Pago TPV ทะลุ $100B/ไตรมาสครั้งแรก (2) **Valuation reset:** MSCI LatAm เทรดที่ ~51% discount เทียบ broader EM (near-record, จาก divergence กับ Asia) และใกล้จุดต่ำสุดในรอบ >20 ปี; MELI EV/Revenue 3.05x = 5-year low ทั้งที่ revenue โต +46% YoY (3) **แต่ margin-compression phase:** ผู้เล่นใหญ่ทุกรายเลือก growth-over-margin — MELI op margin หด 550bps YoY เหลือ 6.7% (Q2'26) จาก free shipping + credit card push + PIX discounts เพื่อป้องกัน share จาก Shopee (Brazil GMV ~$10B ≈ 40% ของ MELI, เพิ่ม ~$6B ในปีเดียว) และ Amazon/Shein; ROIC ของ MELI ร่วงจาก 63.75% (2024) → 14.20% (2026) จาก credit-book scaling + logistics capex. เฉพาะหน้า Fed hawkish (Warsh Jackson Hole, Sept hike ~50/50) → DXY แข็ง → BRL อ่อน (~5.19) → reported USD revenue โดน FX drag 10-18pp (เห็นชัดใน Argentina Q2 +20% reported vs +38% FX-neutral GMV) + de-rating risk ต่อ high-multiple names. ทีม CAUTIOUS ไม่ NEGATIVE เพราะ demand จริง (โต >35% ทุก segment) + valuation base ถูก แต่ยังไม่ POSITIVE เพราะ normalized margin + credit-loss cycle + FX ยัง unresolved — selective เฉพาะชื่อที่มี real MOS บน normalized (ไม่ใช่ peak-recovery) earnings และ distribution/scale moat.",
    keyPoints: [
      "LatAm easing cycle เพิ่งเริ่ม: Brazil Selic 14.00% (cut รอบ 4 ติด, จบปี ~13.75%), Argentina inflation 211%→33% ใน 18 เดือน — tailwind ต่อ consumer credit + e-comm demand + local multiple",
      "Valuation ถูกสุดใน >20 ปี: MSCI LatAm ~51% discount เทียบ EM; MELI EV/Revenue 3.05x = 5-year low ทั้งที่ revenue +46% YoY",
      "Margin-compression เป็น deliberate ทั้งกลุ่ม: MELI op margin -550bps YoY เหลือ 6.7% (Q2'26) จาก free shipping + credit card + PIX discounts เพื่อกัน share จาก Shopee/Amazon/Shein",
      "Fed hawkish + strong USD = EM headwind เฉพาะหน้า: BRL ~5.19 อ่อนจาก Warsh; reported USD growth โดน FX drag 10-18pp (Argentina +20% reported vs +38% FX-neutral GMV)",
      "Credit book scaling เร็ว = risk ใหม่: MELI credit portfolio $7.7B (+91% YoY), ลงทุน $2.1B ในไตรมาสเดียว; ROIC ร่วง 63.75%→14.20% (2024→2026)",
      "Selective: NU/StoneCo แสดงว่า mature LatAm fintech ทำ op margin 50%+ ได้ — MELI credit book มี runway แต่ยัง early; ต้องการ MOS บน normalized margin ไม่ใช่ peak extrapolation",
    ],
    metrics: [
      { label: "MELI revenue growth YoY (Q2'26 reported)", value: 46 },
      { label: "MELI operating margin Q2'26 (%)", value: 6.7 },
      { label: "MELI operating margin YoY change (bps)", value: -550 },
      { label: "Brazil Selic rate (%)", value: 14.0 },
      { label: "MSCI LatAm discount vs broader EM (%)", value: -51 },
    ],
    relatedTickers: ["MELI", "SE", "NU", "STNE"],
    sources: [
      { title: "Central Banking — Brazil cuts rates for a fourth time in a row (Selic 14.00%)", url: "https://www.centralbanking.com/central-banks/monetary-policy/monetary-policy-decisions/7976592/brazil-cuts-rates-for-a-fourth-time-in-a-row" },
      { title: "Rio Times — Brazil Copom Selic 14 percent fourth cut 2026", url: "https://www.riotimesonline.com/brazil-copom-selic-14-percent-fourth-cut-2026/" },
      { title: "Buenos Aires Herald — Milei's economy in 2026: macroeconomic consolidation and politics", url: "https://buenosairesherald.com/economics/mileis-economy-in-2026-between-macroeconomic-consolidation-and-politics" },
      { title: "Rio Times — Argentina Economy 2026: Milei Cuts Inflation to 33%", url: "https://www.riotimesonline.com/argentina-economy-2026-guide/" },
      { title: "Morgan Stanley — Latin America Economic Outlook 2026: A Bull Case for Latam", url: "https://www.morganstanley.com/insights/articles/latin-america-ecnomic-bullish-outlook-2026" },
      { title: "TradingEconomics — Brazilian Real (USD/BRL current ~5.19, Warsh-driven dollar strength)", url: "https://tradingeconomics.com/brazil/currency" },
      { title: "MercadoLibre Q2 2026 earnings (SEC 8-K meli-20260805) — op margin 6.7%, -550bps YoY", url: "https://www.sec.gov/Archives/edgar/data/0001099590/000109959026000021/meli-20260805xex991.htm" },
      { title: "Buenos Aires Times — Amazon and Shopee challenging MercadoLibre's e-commerce dominance", url: "https://www.batimes.com.ar/news/economy/amazon-and-shopee-are-challenging-mercadolibres-e-commerce-market-dominance.phtml" },
    ],
    lastUpdated: "2026-08-29",
    author: "Atlas",
    trigger: "Byproduct of MELI Phase 1 Macro Brief — reveals sector-level view on LatAm e-commerce + fintech (structural growth + valuation reset vs margin-compression phase + Fed-hawkish/strong-dollar EM headwind), applies beyond MELI to SE/NU/STNE/dLocal",
  },
  {
    sector: "US Consumer Fintech / Neobank",
    slug: "us-consumer-fintech-neobank",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle (profitability-pivot phase)",
    headline: "Neobank adoption ของจริง + กลุ่มเข้าสู่ profitability pivot — แต่ interchange regulation ยัง unresolved (Reg II vacated, 8th Cir pending) + near-prime credit normalization + CHYM growth/margin ท้ายกลุ่ม peer",
    thesis: "การวิเคราะห์ CHYM (Chime, 2026-08-31) เปิดเผยมุมมองระดับ sector ที่กว้างกว่าตัวหุ้น — US consumer neobank (CHYM, SOFI, DAVE + adjacency กับ HOOD/NU) กำลังเจอ 3 แรงพร้อมกัน: (1) Profitability pivot — ยุค growth-at-any-cost จบแล้ว, >76% ของ neobank ทั่วโลกยังขาดทุนในปี 2026 (ARPU เฉลี่ย ~$45/ปี vs ~$350 ของธนาคารดั้งเดิม) — ผู้ชนะคือคนที่ diversify เข้า lending/BaaS (Revolut PBT margin 38% ปีที่ 5, Nubank op margin 52%). CHYM ทำ pivot นี้สำเร็จ — GAAP-profitable Q2 2026 (adj EBITDA ~15%), Platform/lending revenue +48% YoY, FCF TTM +$312M. (2) Interchange regulation = sector-wide binary overhang — neobank ส่วนใหญ่พึ่ง debit interchange ผ่าน partner bank <$10B (Durbin exemption, ไม่โดน Reg II cap). ND District Court vacated Reg II ทั้งฉบับ (ส.ค. 2025, stay ระหว่างอุทธรณ์), 8th Circuit ฟัง oral args แล้วปี 2026 รอคำพิพากษา — ถ้า Reg II ถูก vacate ทั้งฉบับ ธนาคารใหญ่ก็เก็บ interchange ไม่ถูก cap → ช่องว่าง exempt/non-exempt แคบลง → neobank เสีย relative advantage; กลับกันถ้า Fed 2023 proposal (ลด cap ~30%) final → ช่องว่างกว้างขึ้น = tailwind. two-directional และยังไม่จบ. (3) Near-prime credit normalization — core demographic ของ neobank กลุ่มนี้ = paycheck-to-paycheck/underbanked; Q2 2026 subprime/small-bank delinquency ~6.4% (~2x ค่าเฉลี่ยรวม), 90+ DPD ขยับขึ้น 2.26% — การเร่ง lending push เข้า demographic นี้ช่วง credit เสื่อม = timing risk (mitigant: Chime lending ส่วนใหญ่ secured/payroll-linked duration สั้น). เชิงบวก: regulatory environment เฉพาะหน้า (2026) โน้ม deregulation — CFPB overdraft rule ถูก Congress ยกเลิกผ่าน CRA (+ ห้ามออก rule คล้ายกัน), EWA interpretive rule น่าจะตายภายใต้ Warsh-era CFPB — net positive ระยะสั้น. ทีม CAUTIOUS ไม่ NEGATIVE เพราะ adoption จริง + profitability pivot ของผู้นำเกิดขึ้นจริง — แต่ยังไม่ POSITIVE เพราะ interchange (สัดส่วนใหญ่ของรายได้) แขวนบน litigation ที่ผลลัพธ์สองทิศ + credit-loss cycle ยังไม่ resolved + valuation กลุ่มตึง (CHYM ~50x fwd P/E, Street PT ~$33-35 = upside จำกัด). selective เฉพาะชื่อที่มี real MOS บน normalized (ไม่ใช่ peak-inflection) earnings + distribution/scale moat หรือ bank charter (SOFI).",
    keyPoints: [
      "Profitability pivot: >76% neobank ทั่วโลกยังขาดทุน 2026; ผู้ชนะ diversify เข้า lending/BaaS — CHYM GAAP-profitable Q2'26 (adj EBITDA ~15%, Platform revenue +48% YoY)",
      "Interchange = sector-wide binary: Reg II vacated (ND Dist. Ct. ส.ค. 2025, stay pending 8th Cir.) — full vacatur บีบช่อง exempt/non-exempt แคบลง (ลบ advantage); Fed 2023 proposal ลด cap 30% = ตรงข้าม (เพิ่ม advantage)",
      "Near-prime credit normalization: subprime/small-bank delinquency Q2'26 ~6.4% (~2x avg), 90+ DPD 2.26% — neobank เร่ง lending เข้า demographic ที่เปราะบางลง",
      "Deregulatory tailwind เฉพาะหน้า: CFPB overdraft rule ถูก Congress ยกเลิกผ่าน CRA + ห้ามออก similar rule; EWA-as-credit interpretive rule น่าจะตาย Warsh-era",
      "CHYM ท้ายกลุ่ม peer: revenue growth 26.4% (ต่ำสุด) + op margin 15.2% (ต่ำสุด) vs SOFI 40.9%/17.3%, DAVE 48.6%/36.0%, NU 44.3%/52.0%, HOOD 38.3%/46.0%",
      "No bank charter = โครงสร้างต่าง: CHYM พึ่ง partner bank (Bancorp/Stride), ไม่มี NIM, ARPU ceiling ต่ำกว่า SOFI ~3x — SOFI (มี charter) = structural comp",
    ],
    metrics: [
      { label: "CHYM revenue growth TTM (YoY %)", value: 26.4 },
      { label: "SOFI revenue growth TTM (YoY %)", value: 40.9 },
      { label: "DAVE revenue growth TTM (YoY %)", value: 48.6 },
      { label: "Neobanks globally unprofitable (%)", value: 76 },
    ],
    relatedTickers: ["CHYM", "SOFI", "DAVE", "HOOD", "NU"],
    sources: [
      { title: "Softjourn — The Top Challenges Confronting Neobanks in 2026 (76% unprofitable, ARPU $45 vs $350)", url: "https://softjourn.com/insights/redefining-resilience-the-top-challenges-confronting-neobanks" },
      { title: "TechBullion — Digital Banking and Neobanks in the U.S. 2026: Where the Profitable Players Now Sit", url: "https://techbullion.com/digital-banking-and-neobanks-in-the-u-s-2026-where-the-profitable-players-now-sit/" },
      { title: "Cooley — District Court Vacates Regulation II's Debit Card Interchange Fee Standard", url: "https://www.cooley.com/news/insight/2025/2025-08-15-district-court-vacates-regulation-iis-debit-card-interchange-fee-standard" },
      { title: "America's Credit Unions — Fed interchange rule challenge heard by appeals court (8th Cir., 2026)", url: "https://www.americascreditunions.org/news-media/news/fed-interchange-rule-challenge-heard-appeals-court" },
      { title: "Congress.gov CRS — Congress Repeals CFPB's Overdraft Rule", url: "https://www.congress.gov/crs-product/IN12513" },
      { title: "TransUnion — Q2 2026 Credit Industry Insights Report", url: "https://newsroom.transunion.com/Q2-2026-CIIR/" },
      { title: "Wolf Street — Credit Card Delinquencies in Q2 2026 (K-shaped, small-bank 6.4%)", url: "https://wolfstreet.com/2026/08/25/credit-card-delinquencies-payment-volume-balances-debt-to-income-and-credit-limits-in-q2-2026-americans-and-their-plastic/" },
      { title: "Investing.com — Chime earnings loom as neobank giant eyes first profitable year", url: "https://www.investing.com/news/earnings/chime-earnings-loom-as-neobank-giant-eyes-first-profitable-year-93CH-4664832" },
      { title: "Crowdfund Insider — US Fintech Firms Chime And SoFi Continue To Increase Competition Among Digital Banks", url: "https://www.crowdfundinsider.com/2026/05/279875-us-fintech-firms-chime-and-sofi-continue-to-increase-competition-among-digital-banks-analysis/" },
    ],
    lastUpdated: "2026-08-31",
    author: "Atlas",
    trigger: "Byproduct of CHYM Phase 1 Macro Brief — reveals sector-level view on US consumer fintech / neobank (profitability-pivot phase + interchange-regulation binary + near-prime credit normalization), applies beyond CHYM to SOFI/DAVE/HOOD/NU",
  },
  {
    sector: "Adtech / Martech",
    slug: "adtech-martech",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle (decelerating)",
    headline: "Secular digital-ad growth is real but decelerating into a constrained, consolidating budget pool — retail media + Meta/Google absorb the growth, the pure-play bellwether (TTD) is de-rating, and Fed-hawkish repricing hits the whole high-multiple cohort — selective, not broad-buy",
    thesis: "การวิเคราะห์ ZETA (Zeta Global, 2026-09-01) เปิดเผยมุมมองระดับ sector ที่กว้างกว่าตัวหุ้น — US adtech/martech (ZETA, TTD, CRTO, APP, BRZE + adjacency กับ retail media ของ AMZN/WMT) กำลังเจอ 4 แรงพร้อมกัน: (1) **Digital ad spend decelerating:** eMarketer คาด US digital ad spend +7.9% ปี 2026 (programmatic display +12.5%, social +15.6%) แต่ growth rate 'normalizing as digital maturity sets in' — คาดชะลอต่อปี 2027+; Meta family แซง Google บน net US ad-revenue basis ครั้งแรก (~$100.9B) — การเติบโตกระจุกที่ social + retail media ไม่ใช่ independent middle. (2) **Retail media = competitive gravity well:** global retail media market >$196B ปี 2026, RMN spend ~$69B และ 'foundational to how retailers drive profitability' ไม่ใช่ incremental อีกต่อไป — Amazon/Walmart Connect/retailer networks ดูดงบที่เคยไหลผ่าน DSP + independent martech; structural headwind สำหรับใครที่ไม่มี first-party retail/commerce data. (3) **Enterprise martech budget constrained แต่ AI เป็น priority:** Gartner 2026 CMO Spend — overall marketing spend +1.7% YoY (อ่อนสุดตั้งแต่ 2021), martech share ของ budget แตะ 5-year low 19.4% (จาก 26.6% ปี 2021) — แต่ 62% ของ CMO วางแผนลงทุน martech เพิ่ม, 15.3% ของ budget ไป AI, 70% บอก AI คือ top priority H2 2026, 56% shift ไป consumption/usage-based pricing → งบหายาก + consolidate ไปหา platform ที่ AI-differentiated + outcome-priced น้อยราย. (4) **AI-in-marketing / agentic AI ยัง unproven ที่ enterprise scale:** 90.3% ของทีมการตลาดรัน AI agent ที่ไหนสักที่ในสแตกแล้ว แต่ 74% ของ martech leader บอก data integration/quality คือ barrier หลัก — narrative tailwind ที่ทุก vendor พูดเหมือนกัน. Bellwether check: The Trade Desk Q2 guide (~$750M) อ่านว่า 'soft', หุ้นร่วงแรงหลัง May call, 'conflicts over margin control ... indicative of a shrinking addressable market' (Digiday); TTD revenue growth TTM ~11.6% vs ZETA 35% total / 25% organic — pure-play DSP model กำลัง mature ขณะที่ identity-graph + owned-channel model ยัง compound. Martech landscape 2026: 15,505 products +0.79% (flattest ใน 15 ปี), 1,488 added / 1,367 removed — consolidation phase, scaled data platform ได้ share จาก point tool แต่ incremental TAM ไม่ขยาย. ทีม CAUTIOUS ไม่ NEGATIVE เพราะ secular adoption จริง + scaled players ที่มี first-party data moat ยังชนะได้ — แต่ยังไม่ POSITIVE เพราะ budget pool หด + retail media/Meta ดูด growth + Fed-hawkish (Sept hike priced) กด high-multiple cohort ทั้งกลุ่ม + ZETA เองมี data-provenance overhang (Culper short report + securities class action Davoodi v. Zeta — MTD denied 8 ก.ค. 2026, เข้าสู่ discovery). selective เฉพาะชื่อที่มี real MOS บน normalized earnings + first-party-data/owned-channel moat.",
    keyPoints: [
      "Digital ad spend decelerating: US +7.9% 2026F (eMarketer), slower 2027+; Meta family แซง Google net US ad revenue ครั้งแรก (~$100.9B) — growth กระจุกที่ social + retail media",
      "Retail media networks = gravity well: global >$196B 2026, RMN spend ~$69B, 'foundational not incremental' — Amazon/Walmart ดูดงบจาก DSP + independent martech",
      "Enterprise martech budget constrained: marketing spend +1.7% YoY (อ่อนสุดตั้งแต่ 2021), martech share 19.4% = 5-yr low — แต่ 62% CMO ลงทุน martech เพิ่ม, 70% บอก AI = top priority, 56% shift ไป consumption pricing",
      "Bellwether de-rating: TTD Q2 guide 'soft', 'shrinking addressable market' (Digiday); TTD growth TTM ~11.6% vs ZETA 25% organic — pure-play DSP maturing",
      "AI-in-marketing crowded + unproven: 90.3% ของทีมรัน AI agent แล้ว แต่ 74% ติด data integration/quality — narrative ที่ทุก vendor อ้างเหมือนกัน",
      "Fed-hawkish (Sept 25bp hike priced, 10Y ~4.8% highest since Jan 2025) กด high-multiple adtech ทั้ง cohort; martech landscape +0.79% = consolidation, TAM ไม่ขยาย",
    ],
    metrics: [
      { label: "US digital ad spend growth 2026F (eMarketer, %)", value: 7.9 },
      { label: "US total marketing spend growth YoY (Gartner, %)", value: 1.7 },
      { label: "Martech % of marketing budget 2026 (5-yr low, Gartner)", value: 19.4 },
      { label: "CMOs planning to increase martech investment (%)", value: 62 },
    ],
    relatedTickers: ["ZETA", "TTD", "CRTO", "APP", "BRZE"],
    sources: [
      { title: "eMarketer — US Ad Spending 2026 (digital +7.9%, programmatic display +12.5%, social +15.6%)", url: "https://www.emarketer.com/content/us-ad-spending-2026" },
      { title: "eMarketer — US ad spending growth normalizes as digital maturity sets in", url: "https://www.emarketer.com/content/us-ad-spending-growth-normalizes-digital-maturity-sets" },
      { title: "Gartner — CMO Spend 2026 (marketing spend +1.7% YoY, martech share 19.4% 5-yr low, 62% plan to invest more, 70% name AI top priority)", url: "https://www.gartner.com/en/articles/cmo-spend" },
      { title: "Chief Marketer — Gartner CMO Spend Survey: Consumption-Based Martech, Paid Media Spend", url: "https://www.chiefmarketer.com/gartner-cmo-spend-survey-budgets-reflect-increase-in-consumption-based-martech-paid-media-spend/" },
      { title: "Digiday — By the numbers: Ad tech's quarter of mixed fortunes (TTD Q2 guide 'soft', shrinking addressable market)", url: "https://digiday.com/media-buying/by-the-numbers-ad-techs-quarter-of-mixed-fortunes/" },
      { title: "MartechSeries — Where AdTech and Retail Media Are Headed in 2026 (retail media >$196B, RMN ~$69B, foundational not incremental)", url: "https://martechseries.com/mts-insights/guest-authors/where-adtech-and-retail-media-are-headed-in-2026/" },
      { title: "everything-PR — AdTech 2026: AI Search Ads, Retail Media, CTV, Cookie Reversal", url: "https://everything-pr.com/adtech-2026-ai-search-ads-retail-media-ctv-and-the-cookie-reversal/" },
      { title: "DigitalApplied — Martech Statistics 2026 (15,505 products +0.79% flattest in 15 yrs; 90.3% run AI agents; 74% cite data integration barrier)", url: "https://www.digitalapplied.com/blog/martech-statistics-2026-data-points" },
      { title: "Campaigns & Elections — 2026 midterms forecast ~$10B+ ad spend (record non-presidential cycle)", url: "https://campaignsandelections.com/industry-news/new-report-forecasts-10-billion-in-midterm-ad-spending/" },
      { title: "Stanford Securities Class Action Clearinghouse — Davoodi v. Zeta Global Holdings Corp. (case 108483; MTD denied Jul 8 2026, in discovery)", url: "https://securities.stanford.edu/filings-case.html?id=108483" },
    ],
    lastUpdated: "2026-09-01",
    author: "Atlas",
    trigger: "Byproduct of ZETA Phase 1 Macro Brief — first sector-level view on adtech/martech (secular growth decelerating + constrained/consolidating budget pool + retail-media crowding-out + Fed-hawkish multiple compression), applies beyond ZETA to TTD/CRTO/APP/BRZE",
  },
  {
    sector: "ACA Marketplace / Managed Care",
    slug: "aca-marketplace-managed-care",
    stance: "NEGATIVE",
    cyclePosition: "Policy-driven downturn / late-cycle (trough unconfirmed)",
    headline: "The demand driver already lapsed — enhanced ACA subsidies expired Jan 1 2026, Congress is stalled, marketplace enrollment is falling 20%+ and every major peer is posting net losses on a sector-wide medical-cost blowout — a two-directional binary catalyst, not a place for new aggressive-growth capital",
    thesis: "การวิเคราะห์ OSCR (Oscar Health, 2026-09-01) เปิดเผยมุมมองระดับ sub-sector ที่กว้างกว่าตัวหุ้น — US ACA marketplace / managed care (OSCR, CNC, MOH, ELV, ALHC) กำลังเจอ 4 แรงพร้อมกัน: (1) **Subsidy cliff เกิดขึ้นแล้ว ไม่ใช่ความเสี่ยงอนาคต:** enhanced premium tax credits (ARPA/IRA-era) หมดอายุจริง 1 ม.ค. 2026. Senate S.3385 (ต่อถึง 2028) ล้มเดือน ธ.ค. 2025 (ไม่ถึง 60 เสียง). House ผ่านร่างต่ออายุ 3 ปี 230–196 เมื่อ 8–9 ม.ค. 2026 แต่สมาชิกยอมรับเองว่า 'likely to fail in the Senate'. compromise ที่ยังมีชีวิตคือ CARE Act (Moreno R-OH + Collins R-ME) — ต่อ 2 ปี + income cap ~$200K/700% FPL + minimum premium ~$25/เดือน (ลบล้าง $0-premium plans) + CSR funding — ณ กลางปี 2026 ยัง stalled, แรงผลักเดียวคือ midterm พ.ย. 2026. (2) **Enrollment กำลังหด:** ACA effectuated enrollment 22.3M (2025) → คาด ~16.5–17.5M (2026, KFF) = −21% ถึง −26% แล้วสำหรับปีนี้; avg subsidized premium payment +114% ($888→$1,904/ปี); CBO คาด benchmark premium +7.7% เพิ่มปี 2027; ~4M คนจะกลายเป็น uninsured. analyst คาด marketplace decline อีก 10–20% สำหรับ 2027 จากฐานที่ลดแล้ว. (3) **MLR blowout ทั้ง sector:** Q2 2026 earnings ตอกย้ำ margin compression พร้อมกัน — ELV Health Benefits op margin 5.0%→3.6% YoY (หุ้น −6.7%, จุดชนวน selloff ทั้งกลุ่ม), MOH −9% premarket, CNC/MOH TTM net margin ติดลบ. สาเหตุ: Medicaid redetermination (เริ่ม เม.ย. 2023) ผลักคนเข้า ACA pool ที่ morbidity สูง + effectuation ต่ำ → market-wide medical cost trend spike; GLP-1 cost surge; lagging Medicaid rates. Healthcare = sole S&P 500 sector ที่ earnings หด YoY ใน Q2 2026 (−18.2%, FactSet). (4) **Medicare Advantage reimbursement pressure:** almost-flat MA rate proposal กด CNC/MOH/ELV เพิ่ม (Morningstar — 'managed care stocks plunge'). ทีมให้ stance NEGATIVE (ไม่ใช่ CAUTIOUS) สำหรับการ deploy เงินใหม่เข้า sub-sector นี้ เพราะ demand driver หลัก lapsed แล้ว + Congress stalled + ทุก peer ขาดทุน + regime = TRANSITIONAL-CAUTIOUS — แต่ยอมรับว่าเป็น **two-directional binary**: ถ้า CARE Act หรือ compromise ใดผ่านก่อน 2027 open enrollment (พ.ย. 2026) + valuations ที่ washed out (CNC <1x book, MOH net loss) → snap-back rally เป็นไปได้แรง. company-specific execution แยกจาก sub-sector call: OSCR เป็น positive outlier (Q2 2026 MLR 79.2% vs 91.1% YoY, swung to GAAP profit, ยก FY2026 earnings-from-ops guide $500–700M) เพราะ re-priced ก่อน peers — แต่ pure-play ACA (98% net premium, ไม่มี Medicaid/MA buffer) = binary exposure สูงสุดในกลุ่ม, beta 2.38. selective เฉพาะชื่อที่มี balance-sheet strength + pricing discipline + real MOS บน normalized (ไม่ใช่ favorable-MLR-year) earnings — และเฉพาะเมื่อ regime กลับเป็น RISK-ON.",
    keyPoints: [
      "Subsidy cliff เกิดแล้ว: enhanced PTCs หมดอายุ 1 ม.ค. 2026; Senate S.3385 ล้ม ธ.ค. 2025; House 3-yr ext (ม.ค. 2026, 230–196) 'likely to fail in Senate'; CARE Act 2-yr compromise (700% FPL cap + $25 min premium) stalled mid-2026",
      "Enrollment หด: ACA effectuated 22.3M (2025) → ~16.5–17.5M (2026F, KFF) = −21–26%; subsidized premium payment +114%; CBO benchmark premium +7.7% เพิ่มปี 2027; analyst คาด marketplace −10–20% เพิ่มปี 2027",
      "MLR blowout sector-wide Q2 2026: ELV Health Benefits op margin 5.0%→3.6% YoY (จุดชนวน selloff), MOH −9% premarket, CNC/MOH TTM net loss; ต้นเหตุ Medicaid-redetermination morbidity spike + GLP-1 cost + lagging Medicaid rates",
      "Healthcare = sole S&P 500 sector ที่ earnings หด YoY ใน Q2 2026 (−18.2%, FactSet); MA almost-flat rate proposal กด CNC/MOH/ELV เพิ่ม",
      "Two-directional binary: CARE Act / compromise ผ่านก่อน พ.ย. 2026 open enrollment + washed-out valuations (CNC <1x book) → snap-back rally เป็นไปได้แรง — จึงไม่ใช่ structural short",
      "OSCR = positive outlier (Q2 2026 MLR 79.2% vs 91.1% YoY, GAAP profit, FY2026 earnings-from-ops guide $500–700M) เพราะ re-priced ก่อน peers — แต่ pure-play ACA, ไม่มี Medicaid/MA buffer, beta 2.38 = binary exposure สูงสุด",
    ],
    metrics: [
      { label: "ACA marketplace enrollment 2025 (M)", value: 22.3 },
      { label: "ACA marketplace enrollment 2026F (M, KFF)", value: 17.5 },
      { label: "Avg subsidized premium payment increase 2026 (%)", value: 114 },
      { label: "CBO benchmark premium increase 2027F additional (%)", value: 7.7 },
    ],
    relatedTickers: ["OSCR", "CNC", "MOH", "ELV", "ALHC"],
    sources: [
      { title: "ASTHO — ACA Enhanced Premium Tax Credits: Legislative Developments in 2025 and 2026", url: "https://www.astho.org/communications/blog/2026/aca-enhanced-premium-tax-credits-legislative-developments-2025-2026/" },
      { title: "HMP — House Passes Bill to Extend ACA Premium Tax Credits", url: "https://www.hmpgloballearningnetwork.com/site/frmc/news/house-passes-bill-extend-aca-premium-tax-credits" },
      { title: "Robertson Stephens — ACA Premium Relief in 2026 (CARE Act: Moreno/Collins, $200K/700% FPL cap, $25 minimum premium)", url: "https://rscapital.com/2026/01/12/will-aca-plan-enrollees-see-premium-relief-soon/" },
      { title: "KFF — ACA Marketplace Premium Payments Would More than Double if Enhanced Premium Tax Credits Expire", url: "https://www.kff.org/affordable-care-act/aca-marketplace-premium-payments-would-more-than-double-on-average-next-year-if-enhanced-premium-tax-credits-expire/" },
      { title: "KFF — What We Know So Far About 2026 ACA Marketplace Enrollment, Premiums, and Deductibles", url: "https://www.kff.org/affordable-care-act/what-we-know-so-far-about-2026-aca-marketplace-enrollment-premiums-and-deductibles/" },
      { title: "Peterson-KFF — How much and why ACA Marketplace premiums are going up in 2027", url: "https://www.healthsystemtracker.org/brief/how-much-and-why-aca-marketplace-premiums-are-going-up-in-2027/" },
      { title: "Modern Healthcare — Centene, Molina, Elevance face unexpected ACA market pressures", url: "https://www.modernhealthcare.com/insurance/mh-centene-molina-elevance-aca-market/" },
      { title: "Yahoo Finance — Insurance stocks fall after Elevance Health results show margin pressure", url: "https://finance.yahoo.com/healthcare/articles/insurance-stocks-fall-elevance-health-112121271.html" },
      { title: "Morningstar — Managed Care Stocks Plunge Following Almost-Flat Medicare Rate Proposal", url: "https://www.morningstar.com/markets/healthcare-managed-care-stocks-plunge-following-almost-flat-medicare-rate-proposal" },
      { title: "Fierce Healthcare — Oscar Health hikes 2026 guidance after strong Q2 (MLR 79.2%, FY26 earnings-from-ops $500–700M)", url: "https://www.fiercehealthcare.com/finance/oscar-health-boosts-2026-earnings-outlook-after-record-profitability-during-first-half-year" },
      { title: "SEC 10-Q Oscar Health oscr-20260630 (MLR, risk-adjustment payable $4.94B)", url: "https://www.sec.gov/Archives/edgar/data/0001568651/000156865126000069/oscr-20260630.htm" },
      { title: "Remodel Health — As Enhanced ACA Tax Credits Expire, ICHRA May Emerge as an Individual Market Stabilizer", url: "https://remodelhealth.com/blog/as-enhanced-tax-credits-sunset-ichra-may-become-market-stabilizer" },
    ],
    lastUpdated: "2026-09-01",
    author: "Atlas",
    trigger: "Byproduct of OSCR Phase 1 Macro Brief — first sector-level view on ACA marketplace / managed care (subsidy cliff already lapsed + Congress stalled + enrollment declining 20%+ + sector-wide MLR blowout + MA rate pressure), applies beyond OSCR to CNC/MOH/ELV/ALHC",
  },
  {
    sector: "Auto Suppliers / Auto Tech",
    slug: "auto-suppliers-auto-tech",
    stance: "CAUTIOUS",
    cyclePosition: "Late-cycle / cyclical trough (turn unconfirmed)",
    headline: "Trading ที่ multiple ถูกสุดในรอบหลายปี — แต่ China structural shift + EV-adoption slowdown + tariff 2-directional overhang ยัง unresolved พร้อมกันสามอย่าง; content-per-vehicle thesis ยัง intact เชิงโครงสร้างแต่ timeline ยืดออก — selective เฉพาะชื่อที่มี real MOS บน normalized (ไม่ใช่ recovery-peak) earnings",
    thesis: "การวิเคราะห์ APTV (Aptiv, 2026-09-06) เปิดเผยมุมมองระดับ sector ที่กว้างกว่าตัวหุ้น — auto suppliers / auto tech (APTV, BWA, LEA, MGA, VC, ADNT, และในเชิง analog overlay: ADI/NXPI/ON auto exposure) กำลังเจอ 4 แรงพร้อมกัน: (1) **Volume ไม่มี tailwind:** US light-vehicle production 2026F ~10.04M units (+1.1% YoY, ฟื้นบางจากการหดตัวปี 2025), US new-vehicle sales ~15.8M (-2.9% YoY, Cox) — flattish-to-down 2026, modest recovery 2027+ (production rise ต่อเนื่องถึง 11.3M by 2030) แต่ไม่มี cyclical upswing ยกทั้งกลุ่ม; affordability (ATP สูง) + Fed hawkish (auto loan 90+ delinquency 5.60% Q1 2026 vs long-term avg 3.59%, subprime auto delinquency = 32-year high) กดยอดขายส่วนล่างของตลาด (2) **China = structural ไม่ใช่ cyclical:** overcapacity ~55.5M คัน/ปี vs demand ~23M (utilization ~50%), price war กด sector-wide auto profit -18% YoY Q1 2026 (avg margin เหลือ ~3.2%), luxury/foreign-brand collapse (BBA sales -260K units 2025, Mercedes -19% YoY, avg luxury price ¥358K→¥344K) — suppliers ที่ขาย content ให้ Western/luxury OEM ที่ export เข้าจีนโดนกระทบถาวร; pivot ไปหา local OEM (BYD/Geely) ได้ volume แต่ content-per-vehicle + supplier margin ต่ำกว่า Aptiv ถึงกับ reclassify China เป็น 'structural headwind' อย่างเป็นทางการใน Q2 2026 (guide cut $300M, หุ้น -17.9% post-print) (3) **EV-adoption slowdown ยืด content thesis:** US federal EV tax credit ($7,500) หมดอายุ 30 ก.ย. 2025 → US new-BEV sales Q1 2026 -28% YoY, US EV market 2026F -15%, plug-in share ค้าง ~8-9% ถึง 2027 (recovery ไม่คาดก่อนปลายทศวรรษ); content-per-vehicle 2-3x บน EV vs ICE ยังจริง และ SDV/zonal architecture/software (~35% ของ vehicle value ในปี 2026) เป็น secular tailwind ของจริง — แต่ content-dollar growth เป็น mid-single-digit ในกรอบ 2026-2027 ไม่ใช่ inflection (4) **Tariff 2-directional:** USMCA/Section 232 auto-parts tariffs = reshoring beneficiary (BWA, US footprint หนัก) vs OEM-cost-passthrough loser (suppliers exposed VW/Stellantis เช่น APTV) — ยังไม่ resolve. **Valuation:** กลุ่มเทรด near-trough (APTV fwd P/E 8.4x / EV/EBITDA 6.4x / normalized FCF yield ~8.5%; BWA, VC ก็ single-digit P/E) = cheap พอที่จะมี MOS ถ้า normalized margin story credible. Margin แผ่กว้างมาก — harness/seating (LEA/MGA op margin 4-5%) vs propulsion/electronics (BWA ~9-10%, Aptiv RemainCo adj EBITDA ~18% หลัง spin EDS ออก) — peer comparison ต้องระวังไม่ใช่ apples-to-apples. ทีมให้ stance CAUTIOUS (ไม่ NEGATIVE เพราะ valuation base ถูกจริง + content thesis เชิงโครงสร้างยัง intact + long-term BEV mix 22.7% ของ NA production by 2030; ไม่ POSITIVE เพราะ China + EV-pace + tariff ยัง unresolved พร้อมกัน และไม่มี volume catalyst) — selective เฉพาะชื่อที่มี real MOS บน normalized (ไม่ใช่ trough หรือ recovery-peak) earnings + margin-mix ที่ทน China local-OEM shift ได้.",
    keyPoints: [
      "Volume ไม่มี tailwind: US production 2026F ~10.04M (+1.1% YoY), sales ~15.8M (-2.9%, Cox) — flattish 2026, modest recovery 2027+; affordability + Fed hawkish (subprime auto delinquency = 32-year high) กดตลาดล่าง",
      "China = structural ไม่ใช่ cyclical: overcapacity ~55.5M vs demand ~23M, price war → sector auto profit -18% YoY Q1 2026 (margin ~3.2%), luxury collapse (BBA -260K units 2025); Aptiv reclassify China เป็น 'structural headwind' อย่างเป็นทางการ",
      "EV-adoption slowdown ยืด content thesis: US EV tax credit หมด 30 ก.ย. 2025 → new-BEV sales Q1 2026 -28% YoY, EV market 2026F -15%, plug-in share ค้าง 8-9% ถึง 2027 — content-per-vehicle 2-3x ยังจริง แต่ dollar growth = mid-single-digit ไม่ใช่ inflection",
      "Tariff 2-directional: reshoring beneficiary (BWA, US footprint) vs OEM-cost-passthrough loser (APTV, exposed VW/Stellantis) — unresolved",
      "Valuation near-trough: APTV fwd P/E 8.4x / EV/EBITDA 6.4x / normalized FCF yield ~8.5%; BWA/VC single-digit P/E — cheap พอมี MOS ถ้า normalized margin credible",
      "Margin แผ่กว้าง — harness/seating (LEA/MGA 4-5%) vs propulsion/electronics (BWA ~9-10%, Aptiv RemainCo adj EBITDA ~18% หลัง spin EDS→Versigent 2026-04-01) — peer comp ต้องระวังไม่ใช่ apples-to-apples",
      "Content-per-vehicle / SDV thesis เชิงโครงสร้างยัง intact (software ~35% ของ vehicle value 2026, zonal architecture, BEV 22.7% ของ NA production by 2030) — แต่ payoff เลื่อนออกไปนอกกรอบ 3-5 ปี",
    ],
    metrics: [
      { label: "US light-vehicle production 2026F growth YoY (%)", value: 1.1 },
      { label: "US new-vehicle sales 2026F growth YoY (%, Cox)", value: -2.9 },
      { label: "US new-BEV sales Q1 2026 YoY (%)", value: -28 },
      { label: "China sector-wide auto profit Q1 2026 YoY (%)", value: -18 },
      { label: "APTV fwd P/E (2026E adj EPS)", value: 8.4 },
      { label: "APTV EV / 2026E EBITDA (x)", value: 6.4 },
    ],
    relatedTickers: ["APTV", "BWA", "LEA", "MGA", "VC"],
    sources: [
      { title: "Cox Automotive — 2026 Outlook: Strategic Themes and Sales Forecast for the Automotive Industry", url: "https://www.coxautoinc.com/insights/2026-outlook-strategic-themes-and-sales-forecast-for-the-automotive-industry/" },
      { title: "Cox Automotive — June 2026 U.S. Auto Sales Forecast (~15.8M units, -2.9% YoY)", url: "https://www.coxautoinc.com/insights/cox-automotive-forecast-june-2026-u-s-auto-sales-forecast/" },
      { title: "Fastmarkets — EV pivot by automakers will likely drive 2026 US auto production trends (~10.04M units +1.1%, BEV share 7.9%→22.7% by 2030)", url: "https://www.fastmarkets.com/insights/ev-pivot-by-automakers-will-likely-drive-2026-us-auto-production-trends-analysts/" },
      { title: "TradingEconomics — Car Production Forecast 2026/2027 (US rises to 11.3M by 2030)", url: "https://tradingeconomics.com/forecast/car-production" },
      { title: "Seafarer Funds — Nobody Wins in a Price War: Destructive Competition in China (overcapacity 55.5M vs demand 23M)", url: "https://www.seafarerfunds.com/prevailing-winds/destructive-competition-in-china/" },
      { title: "36Kr — 2026 Landscape (Part 2): Automobile Manufacturers' Loss of Pricing Power (sector profit -18% Q1 2026, margin 3.2%, luxury price ¥358K→¥344K)", url: "https://eu.36kr.com/en/p/3679596382269057" },
      { title: "Rest of World — China's EV export surge reshapes global auto markets (NEV exports +112.6% YoY May 2026)", url: "https://restofworld.org/2026/china-ev-exports-overcapacity-global-markets/" },
      { title: "Automotive World — China summons automakers again over irrational price war", url: "https://www.automotiveworld.com/topics/e-mobility/china-summons-automakers-again-over-irrational-price-war/" },
      { title: "EVTech.News — New EV Sales Plunge Nearly 28% in U.S. Q1 2026 as Federal Tax Credits End", url: "https://evtech.news/news/new-ev-sales-plunge-nearly-28-in-us-q1-2026-as-federal-tax-credits-end-while-used-ev-demand-hits-record-highs.html" },
      { title: "Fox Business — Americans are pumping the brakes on electric vehicle adoption: 'Affordability is a big issue'", url: "https://www.foxbusiness.com/lifestyle/americans-pumping-brakes-electric-vehicle-adoption-affordability-big-issue" },
      { title: "WardsAuto — Auto loan delinquency rates increased more slowly in Q1 (90+ day 5.60% vs long-term avg 3.59%)", url: "https://www.wardsauto.com/news/auto-loan-delinquency-rates-increased-more-slowly-in-q1/820045/" },
      { title: "Symend — The Auto Loan Crisis: Why Traditional Collections Won't Work in 2026 (subprime auto delinquency 32-year high)", url: "https://www.symend.com/blog/the-auto-loan-crisis-why-traditional-collections-wont-work-in-2026" },
      { title: "Simply Wall St — Aptiv Stock And Two Auto Suppliers Worth Watching For Tariff Driven Supply Chain Shifts (VW/Stellantis tariff exposure)", url: "https://simplywall.st/stocks/us/automobiles/nyse-aptv/aptiv/news/aptiv-stock-and-two-auto-suppliers-worth-watching-for-tariff" },
      { title: "GM Insights — Software-Defined Vehicle Market Size, Growth Trends 2026-2035 (SDV market $447.55B 2026)", url: "https://www.gminsights.com/industry-analysis/software-defined-vehicle-market" },
      { title: "Businesswire — Aptiv Reports Q2 2026 Financial Results (guide cut $300M, China structural headwind)", url: "https://www.businesswire.com/news/home/20260804874546/en/" },
    ],
    lastUpdated: "2026-09-06",
    author: "Atlas",
    trigger: "Byproduct of APTV Phase 1 Macro Brief — first sector-level view on auto suppliers / auto tech (no volume tailwind + China structural shift + EV-adoption slowdown + tariff 2-directional overhang, vs near-trough valuation + intact content-per-vehicle thesis), applies beyond APTV to BWA/LEA/MGA/VC",
  },
  {
    sector: "Auto Aftermarket / Collision-Repair Parts Distribution",
    slug: "auto-aftermarket-collision-parts",
    stance: "CAUTIOUS",
    cyclePosition: "Late-cycle defensive (maintenance demand non-discretionary) — but collision sub-segment in structural volume deflation",
    headline: "Aging-fleet secular tailwind ของจริงและหนุนทั้ง demand pool — แต่ collision-parts sub-segment เจอ claims-frequency deflation + total-loss mix shift + ADAS displacement พร้อมกัน; retail names (ORLY/AZO) แข็งแต่จ่าย premium multiple, distribution/collision names (LKQ/GPC/AAP) ถูกแต่ ROIC เสื่อมเข้าใกล้ WACC — selective, ไม่ broad-buy",
    thesis: "การวิเคราะห์ LKQ (2026-09-08) เปิดเผยมุมมองระดับ sub-sector ที่แยกจาก entry 'Auto Suppliers / Auto Tech' (OEM-supply) เดิม — auto aftermarket / collision-repair parts distribution (LKQ, GPC, DORM ฝั่ง distribution/supplier; ORLY, AZO, AAP ฝั่ง retail store) เจอ dynamic ที่ต่างจาก OEM supply chain สิ้นเชิง: demand ไม่ผูกกับ new-vehicle production แต่ผูกกับ (ก) car parc + vehicle age, (ข) miles driven, (ค) collision claim frequency, (ง) insurer parts-mix policy. **แรงหนุนเชิงโครงสร้าง (บวกทั้ง sub-sector):** avg US vehicle age ทำสถิติ 12.8 ปี (passenger cars 14.5 ปี), scrappage นิ่ง 4.5%, new-vehicle affordability แย่ลงจาก Fed hawkish (ATP สูง + auto-loan rate สูง) → เจ้าของยืดอายุรถ → demand pool ของ out-of-warranty aftermarket/recycled parts โตต่อเนื่อง; รถอายุ >7 ปี = 45% ของ repairable claims ปี 2025 (+9 pts vs 2019) และเป็นกลุ่มที่ ADAS calibration ยังแตะไม่ถึง; repair/maintenance cost +45% ใน 5 ปี ทำให้ insurers มี incentive spec alternative (non-OEM) parts เพื่อคุม claim severity. **แรงกดดันเชิงโครงสร้าง (เฉพาะ collision sub-segment — LKQ/GPC collision exposure):** repairable collision claims หดตัว −10%+ ในปี 2025 และคาดหดต่อปี 2026 (safer cars + ADAS ป้องกันการชน + miles/driver ยังต่ำกว่า pre-2019 marginally); total-loss frequency ทำสถิติ 23.1% ของ claims ทั้งหมด (รถ total = ไม่ซื้ออะไหล่ซ่อม); ADAS calibration ปรากฏบน 28.3% ของ repairable appraisals (จาก 21.8%, +30% YoY) — รถใหม่ที่มี ADAS ต้องใช้ OEM parts + calibration ไม่ใช่ recycled/aftermarket; collision severity −2.5% YoY H1 2026. **แรงต่างระหว่าง retail vs distribution:** retail auto-parts (ORLY op margin 20%, ROIC ~23%; AZO op margin 19%, ROIC ~28%) demand เป็น maintenance/DIY/DIFM ที่ non-discretionary และ non-collision → resilient, gross margin ~52%, pricing power สูง — แต่เทรด premium (ORLY EV/EBITDA ~25x, AZO ~15x) ราคา price-in tailwind หมดแล้ว. Distribution/collision (LKQ EV/EBITDA 8.2x / fwd P/E 8.5x / FCF yield 9.7%; GPC EV/EBITDA ~12.8x; AAP distressed ROIC ~0%) ถูกกว่ามาก แต่ margin กำลังถูกบีบ (LKQ operating margin 11.3%→7.2% ใน 4 ปี, ROIC 11.4%→6.4% เข้าใกล้ WACC ~6.5–7%) — cheap อาจ justified บางส่วนถ้า normalized margin กู้ไม่กลับ. **Cyclical swing factor ปี 2027:** auto insurance premium hikes moderating (จาก double-digit ปี 2023–24 เหลือ +1% H1 2026) → sticker shock ลด → miles driven / claim frequency อาจฟื้นในปี 2027; European collision/mechanical demand อ่อน (consumer weak, German recession) + FX (USD แข็งจาก Fed hawkish กด reported สำหรับ names ที่มี Europe exposure เช่น LKQ 46% ของ revenue). ทีมให้ stance **CAUTIOUS** (ไม่ NEGATIVE เพราะ aging-fleet demand pool โตจริง + collision repair เป็น non-deferrable + valuation base ของ distribution names ถูกจริง; ไม่ POSITIVE เพราะ collision-volume deflation เชิงโครงสร้าง + retail names แพง + Fed hawkish กด levered/dividend-value names + Europe demand/FX headwind) — selective เฉพาะชื่อที่มี real MOS บน normalized (ไม่ใช่ through-cycle-peak) margin/ROIC และ ROIC-recovery ที่ credible.",
    keyPoints: [
      "Demand pool secular tailwind (บวกทั้ง sub-sector): avg US vehicle age 12.8 ปี record (passenger cars 14.5), affordability squeeze จาก Fed hawkish → ยืดอายุรถ; รถ >7 ปี = 45% ของ repairable claims (+9 pts vs 2019) และ ADAS แตะไม่ถึง",
      "Collision sub-segment structural pressure (LKQ/GPC): repairable claims −10%+ ปี 2025 คาดหดต่อ 2026; total-loss frequency record 23.1% (totaled = ไม่ซื้ออะไหล่ซ่อม); ADAS calibration บน 28.3% ของ appraisals (+30% YoY) = รถใหม่ใช้ OEM ไม่ใช่ recycled/aftermarket",
      "Retail vs distribution split: ORLY/AZO (op margin 19–20%, ROIC 23–28%, GM ~52%, non-collision maintenance demand resilient) แต่เทรด premium (ORLY EV/EBITDA ~25x, AZO ~15x); LKQ/GPC/AAP ถูกกว่ามาก (LKQ EV/EBITDA 8.2x, FCF yield 9.7%) แต่ margin/ROIC ถูกบีบ",
      "LKQ-specific: operating margin 11.3%→7.2% ใน 4 ปี, ROIC 11.4%→6.4% เข้าใกล้ WACC ~6.5–7% = value-trap flag; + Germany ERP self-inflicted disruption Q2 2026 (−$140M revenue / −$50M EBITDA) + FY2026 EPS guide cut เป็น $2.60–2.90; NA organic +0.5% Q2 2026 = first growth since 2023 (tentative inflection)",
      "Cyclical swing 2027: insurance premium hikes moderating (+1% H1 2026 vs double-digit 2023–24) → sticker shock ลด → miles/claims อาจฟื้น; แต่ Europe demand อ่อน + USD แข็ง (Fed hawkish) กด names ที่มี Europe exposure (LKQ 46% ของ revenue)",
      "Insurer parts-mix = key dependency: repair cost +45%/5 ปี → insurers มี incentive spec alternative (non-OEM) parts; regulatory right-to-repair momentum หนุน aftermarket — แต่ downside ถ้า jurisdiction ใดจำกัด non-OEM crash parts",
    ],
    metrics: [
      { label: "Avg US vehicle age 2025 (years, record)", value: 12.8 },
      { label: "Repairable collision claims YoY 2025 (%)", value: -10 },
      { label: "Total-loss frequency 2025 (% of all claims, record)", value: 23.1 },
      { label: "ADAS calibration penetration 2025 (% of repairable appraisals)", value: 28.3 },
      { label: "LKQ EV/EBITDA (x, deep-value end)", value: 8.2 },
      { label: "ORLY EV/EBITDA (x, premium end)", value: 25 },
    ],
    relatedTickers: ["LKQ", "GPC", "DORM", "ORLY", "AZO", "AAP"],
    sources: [
      { title: "CCC Intelligent Solutions — Crash Course 2026 Report: Higher Severity and Record Total Loss Frequency (repairable claims −10%+, total-loss 23.1%, ADAS calibration 28.3%, vehicles >7yr = 45% of claims)", url: "https://ir.cccis.com/news-releases/news-release-details/ccc-crash-course-2026-report-finds-higher-severity-and-record" },
      { title: "S&P Global Mobility — Average age of vehicles in the US rises to 12.8 years in 2025", url: "https://aftermarketinsight.spglobal.com/news/4375/average-age-of-vehicles-in-the-us-rises-to-128-years-in-2025" },
      { title: "Repairer Driven News — Average passenger car age now 14.5 years, nearly 13 years overall", url: "https://www.repairerdrivennews.com/2025/05/28/average-passenger-car-age-now-14-5-years-nearly-13-years-overall/" },
      { title: "Autobody News — 2025 Data Points to Fewer Claims, More Collision Repair Complexity in 2026", url: "https://www.autobodynews.com/news/2025-data-points-to-fewer-claims-more-collision-repair-complexity-in-2026" },
      { title: "InsureMojo — Record 23.1% of Auto Claims Are Total Losses in 2025", url: "https://www.insuremojo.com/total-loss-rate-record-auto-repair-costs-2026/" },
      { title: "CarInsurance.com — State of Auto Insurance in 2026 (collision severity −2.5% YoY H1 2026, repair cost +45% over 5 years)", url: "https://www.carinsurance.com/state-of-auto-insurance/" },
      { title: "Insurify — Car Insurance Costs Climb in the First Half of 2026 (full-coverage premium +1% H1 2026, moderating)", url: "https://insurify.com/car-insurance/report/" },
      { title: "PartsTrader — Predicting Claims Volume in 2026: Key Factors to Watch", url: "https://www.partstrader.com/predicting-claims-volume-in-2026-key-factors-to-watch/" },
      { title: "Yahoo Finance — LKQ Q2 Earnings Miss Estimates on Europe ERP Disruption (guidance cut, NA organic +0.5% first since 2023)", url: "https://finance.yahoo.com/markets/stocks/articles/lkq-q2-earnings-miss-estimates-161200750.html" },
      { title: "StockAnalysis.com — LKQ ratios (EV/EBITDA 8.2x, ROIC 6.35%, operating margin trend)", url: "https://stockanalysis.com/stocks/LKQ/financials/ratios/" },
      { title: "GuruFocus — O'Reilly Automotive ROIC (~23%) / AutoZone EV/EBITDA (~15x)", url: "https://www.gurufocus.com/term/roic/ORLY" },
      { title: "Macrotrends — O'Reilly Automotive EBITDA Margin (retail model ~22%)", url: "https://www.macrotrends.net/stocks/charts/ORLY/oreilly-automotive/ebitda-margin" },
    ],
    lastUpdated: "2026-09-08",
    author: "Atlas",
    trigger: "Byproduct of LKQ Phase 1 Macro Brief — first sector-level view on auto aftermarket / collision-repair parts distribution (aging-fleet demand tailwind vs claims-frequency deflation + total-loss mix shift + ADAS displacement; retail resilient-but-premium vs distribution cheap-but-margin-pressured), distinct from the OEM-supply 'Auto Suppliers / Auto Tech' entry; applies beyond LKQ to GPC/DORM/ORLY/AZO/AAP",
  },
  {
    sector: "Energy",
    slug: "energy",
    stance: "NEGATIVE",
    cyclePosition: "Late-cycle",
    headline: "War premium ยกระดับสู่ของจริง — Brent ทะลุ $100 ครั้งแรกตั้งแต่ ก.ค. หลังสหรัฐฯ จมเรือน้ำมันอิหร่าน 3-5 ลำ, Hormuz flows <2M bpd; XLE/majors วิ่งแล้ว +33-38% YTD — เข้าซื้อตอนนี้ = จ่ายที่ war-premium peak, NEGATIVE คงเดิม (เข้มขึ้น)",
    thesis: "อัปเดตต่อยอด Energy entry เดิม (31 ก.ค. 2026 Brent ~$89-90, NEGATIVE) จาก Atlas Macro Regime re-call 2026-09-11 — สถานการณ์ยกระดับชัดเจนจนต้องบันทึกแยก: US-Iran conflict เข้าเดือนที่ 7 และ escalate แรง สหรัฐฯ ใช้กำลังทหารทำลายเรือบรรทุกน้ำมันดิบอิหร่าน 3-5 ลำ (8-10 ก.ย.) ตอบโต้การโจมตีเรือรบสหรัฐฯ + กลุ่มฮูตีโจมตีโรงงานพลังงานซาอุฯ ต่อเนื่อง → crude flows ผ่าน Strait of Hormuz ร่วงต่ำกว่า 2 ล้านบาร์เรล/วัน (จาก ~8-9 ล้านก่อนสงคราม), floating storage ถูกดึงออก ~190 ล้านบาร์เรลตั้งแต่กลาง ก.ค. Brent (Nov contract) ทะลุ **$100-102/bbl ครั้งแรกตั้งแต่ ก.ค.**, WTI ~$96-101 นักวิเคราะห์แห่ขึ้น forecast — Morgan Stanley คาด Brent เฉลี่ย $100 ใน Q4, Goldman/BofA/HSBC ปรับขึ้นทั้งหมด, Goldman เตือน risk >$120 ถ้าการโจมตีเรือขนส่งรุนแรงขึ้น. **แต่ stance ยังคง NEGATIVE และเข้มขึ้น** ไม่ใช่พลิกบวก — เพราะ thesis เดิมยังจริงและตอนนี้จริงกว่าเดิม: (1) ราคาปัจจุบันขับเคลื่อนด้วย geopolitical risk premium ล้วนๆ ไม่ใช่ structural scarcity — EIA ยังคาด oversupply ~2.2 mb/d ปี 2026, การ de-escalate จริงจังจะทำให้ premium ก้อนนี้ collapse เร็วและแรง (2) equity ในกลุ่มวิ่งไปมากแล้ว — XLE +7.6% ใน 30 วัน, XOM +33% / CVX +38% YTD 2026 — valuation ตึงและ price-in war premium ไปพอสมควร (3) earnings pattern peak-then-decline ที่ FactSet เคย verify (Q2 2026 Energy +122.9% YoY ลดหลั่นจนพลิกลบ -26.3% Q2 2027) ยังเป็น consensus — การซื้อตอนนี้ = จ่ายที่ earnings peak + valuation แพง + war premium สูงสุด พร้อมกันสามชั้น สำหรับ time horizon 3-5 ปีของกองทุน. เพิ่มเติม: Fed hawkish (>73% hike priced Sept FOMC post-PPI) + regime = TRANSITIONAL-CAUTIOUS → ไม่ใช่ทั้งจังหวะและไม่ใช่ทั้ง sector สำหรับเงินทุนใหม่. ถ้าจำเป็นต้องมี exposure จริง: integrated majors (XOM/CVX) หรือ midstream/pipeline ที่ FCF นิ่งกว่า ดีกว่า pure-play E&P ที่จะโดนแรงสุดถ้า cycle หัน.",
    keyPoints: [
      "Brent ทะลุ $100-102/bbl (10 ก.ย. 2026) ครั้งแรกตั้งแต่ ก.ค. — สหรัฐฯ จมเรือน้ำมันอิหร่าน 3-5 ลำ, ฮูตีโจมตีโรงงานซาอุฯ, Hormuz crude flows <2M bpd (จาก ~8-9M)",
      "นักวิเคราะห์ปรับขึ้น forecast พร้อมกัน: MS Brent avg $100 Q4, Goldman/BofA/HSBC ขึ้นทั้งหมด, Goldman เตือน >$120 risk — แต่เป็น risk-premium driven ไม่ใช่ scarcity (EIA ยังคา oversupply ~2.2 mb/d 2026)",
      "Energy equity วิ่งไปแล้ว: XLE +7.6% 30d, XOM +33% / CVX +38% YTD 2026 — valuation ตึง, war premium price-in ไปมาก, downside แรงถ้า de-escalate",
      "Earnings peak-then-decline ยัง consensus (FactSet: Energy +122.9% YoY Q2'26 → -26.3% Q2'27) — ซื้อตอนนี้ = จ่ายที่ earnings peak + valuation แพง + war premium สูงสุด สามชั้นพร้อมกัน",
      "Regime TRANSITIONAL-CAUTIOUS + Fed hawkish (>73% Sept hike) — ไม่ใช่จังหวะเพิ่มทุนใหม่เข้า sector ใดๆ โดยเฉพาะ sector ที่ราคาพึ่ง geopolitical premium",
      "ถ้าต้อง exposure: integrated majors (XOM/CVX) / midstream ดีกว่า pure-play E&P ที่ leverage ต่อ cycle turn สูงสุด",
    ],
    metrics: [
      { label: "Brent crude ปัจจุบัน (10 ก.ย. 2026, USD/bbl)", value: 101 },
      { label: "Hormuz crude flows ปัจจุบัน (M bpd, จาก ~8-9M)", value: 2 },
      { label: "XOM YTD return 2026 (%)", value: 33 },
      { label: "CVX YTD return 2026 (%)", value: 38 },
      { label: "S&P 500 Energy earnings growth Q2 2027F (YoY %)", value: -26.3 },
    ],
    relatedTickers: ["XLE", "XOM", "CVX"],
    sources: [
      { title: "CNBC — Oil extends gains, Brent above $101 after U.S. destroys Iranian oil tankers", url: "https://www.cnbc.com/2026/09/10/iran-us-oil-hormuz-supply-trump-military-brent-wti.html" },
      { title: "Benzinga — Brent Crude Oil Price Tops $100 as Morgan Stanley Rings the Alarm Bell", url: "https://www.benzinga.com/markets/prediction-markets/26/09/61686144/brent-100-morgan-stanley-stock-risks" },
      { title: "24/7 Wall St — Oil Just Blew Past $100 a Barrel and These 5 Energy Stocks Are in the Line of Fire (XLE +7.6% 30d, XOM +33%, CVX +38% YTD, Hormuz flows <2M bpd, Goldman >$120 risk)", url: "https://247wallst.com/investing/2026/09/10/oil-just-blew-past-100-a-barrel-and-these-5-energy-stocks-are-in-the-line-of-fire/" },
      { title: "OilPrice.com — Oil Breaks $100 and This Rally Has Legs", url: "https://oilprice.com/Energy/Crude-Oil/Oil-Breaks-100and-This-Rally-Has-Legs.html" },
      { title: "FactSet Insight — S&P 500 Energy Sector Earnings Preview: Q2 2026 (quarterly YoY growth, peak-then-decline)", url: "https://insight.factset.com/sp-500-energy-sector-earnings-preview-q2-2026" },
      { title: "Global News — EIA raises oil output forecast, says oversupply will weigh on prices in 2026", url: "https://globalnews.ca/news/11523165/eia-oil-price-forecast-oversupply-2026/" },
    ],
    lastUpdated: "2026-09-11",
    author: "Atlas",
    trigger: "Regime re-call 2026-09-11 — US-Iran military escalation pushed Brent >$100 (first since July), materially changes the facts underlying the 2026-07-31 Energy entry (Brent $89); stance NEGATIVE unchanged but reinforced (war-premium peak, not a scarcity story)",
  },
  {
    sector: "Software / AI",
    slug: "software-ai",
    stance: "CAUTIOUS",
    cyclePosition: "Mid-cycle",
    headline: "Secular growth ยังของจริง แต่ตอนนี้เจอ double whammy — ROI-realization overhang เดิม + rate-repricing shock ใหม่ (Fed >73% hike priced, 10Y highest since 2023, oil-driven inflation); ยัง selective ไม่ broad-avoid แต่ downgrade-lean",
    thesis: "อัปเดต Software/AI entry เดิม (30 ก.ค. 2026, CAUTIOUS) จาก Atlas Macro Regime re-call 2026-09-11 — thesis หลักไม่เปลี่ยน (AI capex ยังโตแรง, backlog/cloud growth ยังเป็นหลักฐาน ROI จริงสำหรับผู้ชนะที่ชัดเจน, แต่ช่องว่าง capex-vs-ROI ยังเป็น bull/bear pivot) — สิ่งที่เปลี่ยนคือ **macro overlay กดดันขึ้นชัดเจน**: (1) Fed hawkish ยืนยันแล้ว ไม่ใช่แค่ความเสี่ยง — post-PPI (10 ก.ย.) CME FedWatch แสดง >73% odds ของ 25bps hike ที่ FOMC 15-16 ก.ย., zero cuts priced เข้าไปถึง 2028, UBS/BofA/Deutsche ย้าย forecast เป็น hike ทั้ง Sept และ Dec (2) 10Y Treasury yield แตะ ~4.85% สูงสุดตั้งแต่ พ.ย. 2023 — discount rate ที่ใช้ตีมูลค่า long-duration software cash flow ขยับขึ้นจริง (3) oil shock (Brent >$100) = inflation re-acceleration risk ที่ทำให้ Fed มีเหตุผล higher-for-longer นานขึ้น. high-multiple software เป็น cohort ที่ sensitive ที่สุดต่อ 3 แรงนี้พร้อมกัน — และหลักฐานเชิงประจักษ์จากพอร์ตเราเองยืนยัน: S&P 500 ร่วง 4 วันติด (4-9 ก.ย.) นำโดย tech, Nasdaq underperform, ADBE/NOW/CRM/GOOGL ทั้งหมดโดน sell-the-news ซ้ำๆ ทุกครั้งที่มีข่าว capex หรือ rate แม้ fundamentals จริงจะแข็งขึ้นต่อเนื่อง. ทีมยัง CAUTIOUS ไม่ยกเป็น NEGATIVE เพราะ (ก) demand จริง — Technology sector Q2 2026 earnings +64.6% YoY เร่งขึ้น, cloud growth ของผู้นำ (GOOGL Cloud +82%) ยังเป็นหลักฐาน ROI ที่จับต้องได้ (ข) valuation กลุ่ม software/services ร่วงกลับมาใกล้ระดับ 'peak uncertainty' ที่ Morgan Stanley เคยเรียก = downside บางส่วน price-in แล้ว — แต่ downgrade-lean: regime TRANSITIONAL-CAUTIOUS + rate repricing ยังไม่จบ + CPI/FOMC binary สัปดาห์นี้ → ไม่ใช่จังหวะเพิ่มทุนใหม่เข้ากลุ่ม, selective เฉพาะผู้ชนะที่มี real cloud/backlog ROI + margin ที่ทน rate ได้.",
    keyPoints: [
      "Double whammy: ROI-realization overhang เดิม + rate-repricing shock ใหม่ — Fed >73% hike priced (post-PPI 10 ก.ย.), zero cuts เข้า 2028, UBS/BofA/Deutsche ย้ายเป็น Sept+Dec hike",
      "10Y Treasury ~4.85% สูงสุดตั้งแต่ พ.ย. 2023 — discount rate สำหรับ long-duration software cash flow ขยับขึ้นจริง; oil >$100 = inflation re-accel risk → higher-for-longer นานขึ้น",
      "หลักฐานตลาด: S&P 500 ร่วง 4 วันติด (4-9 ก.ย.) นำโดย tech, Nasdaq underperform; ADBE/NOW/CRM/GOOGL โดน sell-the-news ซ้ำทุกข่าว capex/rate",
      "ยัง CAUTIOUS ไม่ NEGATIVE: demand จริง (Tech Q2'26 earnings +64.6% YoY เร่งขึ้น, GOOGL Cloud +82%), valuation กลุ่มร่วงมาใกล้ 'peak uncertainty' ระดับที่ MS เคยเรียก = downside บางส่วน price-in",
      "Downgrade-lean: regime TRANSITIONAL-CAUTIOUS + rate repricing ยังไม่จบ + CPI/FOMC binary สัปดาห์นี้ — ไม่ใช่จังหวะเพิ่มทุนใหม่, selective เฉพาะผู้ชนะที่ ROI จับต้องได้ + margin ทน rate",
    ],
    metrics: [
      { label: "CME FedWatch Sept hike odds post-PPI (%)", value: 73 },
      { label: "10Y Treasury yield ปัจจุบัน (%)", value: 4.85 },
      { label: "S&P 500 consecutive down sessions (4-9 ก.ย.)", value: 4 },
      { label: "Technology sector Q2 2026 earnings growth YoY (%)", value: 64.6 },
    ],
    relatedTickers: ["ADBE", "NOW", "GOOGL", "CRM", "ADSK"],
    sources: [
      { title: "24/7 Wall St — Tomorrow's CPI Report Could Send Rate-Hike Odds Even Higher (>73% post-PPI CME FedWatch)", url: "https://247wallst.com/investing/2026/09/10/tomorrows-cpi-report-could-send-rate-hike-odds-even-higher/" },
      { title: "CNBC — 10-year Treasury yield touches highest since 2023 despite Bessent's $6 billion bond buyback plan", url: "https://www.cnbc.com/2026/09/09/treasury-yields-oil-inflation.html" },
      { title: "TheStreet — Stock Market Today Sept 9 2026 (Dow/Russell fall, Brent >$101, yields new 52wk highs, 3rd consecutive session down)", url: "https://www.thestreet.com/stock-market-today/stock-market-today-dow-jones-sp-500-nasdaq-updates-sept-09-2026" },
      { title: "Chase — September 2026 rate hike now expected amid energy shocks", url: "https://www.chase.com/personal/investments/learning-and-insights/article/september-2026-rate-hike-now-expected-amid-energy-shocks" },
      { title: "Forbes — S&P 500 Earnings Outlook Hinges On Tech, Energy And The Fed", url: "https://www.forbes.com/sites/bill_stone/2026/07/05/sp-500-earnings-outlook-hinges-on-tech-energy-and-the-fed/" },
    ],
    lastUpdated: "2026-09-11",
    author: "Atlas",
    trigger: "Regime re-call 2026-09-11 — Fed-hawkish confirmed (>73% Sept hike post-PPI) + 10Y at 2023-highs + oil-driven inflation stack an acute rate-repricing headwind on top of the existing ROI-realization overhang; core thesis unchanged, stance CAUTIOUS held with downgrade-lean",
  },
  {
    sector: "IT Services / Consulting",
    slug: "it-services-consulting",
    stance: "NEGATIVE",
    cyclePosition: "Structural disruption + cyclical demand trough",
    headline: "AI กำลังเปลี่ยน economics ของ consulting เร็วกว่าที่ incumbent ปรับตัวได้ + Middle East war กด discretionary spend โดยตรง — ACN bookings -2% YoY, guide 3-4% local currency; NEGATIVE สำหรับเงินทุนใหม่",
    thesis: "First sector-level view สำหรับ IT services / consulting (ACN, IBM consulting, INFY/WIT/CTSH offshore, และ Big 4 advisory ในเชิง analog) — byproduct ของ Atlas Macro Regime re-call 2026-09-11 ที่พบ direct macro-to-sector linkage: การวิเคราะห์ demand consulting พบว่า Middle East war (US-Iran เดือนที่ 7, Brent >$100) กำลังกด discretionary IT/consulting spend โดยตรง — Accenture CEO Julie Sweet บอก analyst บน Q3 FY2026 call ตรงๆ ว่า 'lower discretionary spend impacts consulting work' และ new bookings ร่วง ~2% YoY ($19.3B vs $19.7B ปีก่อน) พร้อมกับ FY2026 revenue guide แค่ 3-4% local currency (6% USD). ปัญหาใหญ่กว่า cyclical คือ **structural AI disruption**: ตลาดสรุปแล้วว่า generative AI เป็น net-negative ต่อ services firms — time-and-materials billing model (ขายชั่วโมงคน) โดนกระทบตรงจุดเมื่อ AI ทำให้ deliverable เดิมใช้คนน้อยลง; key risk ตามที่ analyst หลายสำนักระบุคือ 'AI เปลี่ยน economics ของ consulting เร็วกว่าที่ Accenture ปรับตัวได้'. 66% ของ enterprise buyer ใช้ platform-first strategy (ซื้อ software platform แทนจ้าง integrator), 67% รัน GenAI ใน production แล้ว, 75% วางแผนเพิ่ม AI budget — แต่เม็ดเงินไหลไป platform/software vendor ไม่ใช่ labor-arbitrage consulting. เชื่อมโยงพอร์ตโดยตรง: ACN เป็น position ที่ถูก trim 50% ไปแล้ว (stop breach มิ.ย. 2026, Q3 FY26 rev miss + guide cut) — sector call นี้ยืนยันว่าปัญหา ACN ไม่ใช่ company-specific ล้วนๆ แต่เป็น sector-wide structural + cyclical พร้อมกัน. Indian IT (INFY/WIT/TCS) ก็ร่วงตาม ACN outlook ('weak Accenture outlook revives fears of AI-led disruption, IT stocks reel'). ทีมให้ stance **NEGATIVE** (ไม่ใช่ CAUTIOUS) สำหรับเงินทุนใหม่เข้า sub-sector นี้ เพราะ demand driver อ่อนทั้ง cyclical (war/discretionary) และ structural (AI disruption + platform-first) พร้อมกัน + regime TRANSITIONAL-CAUTIOUS + ไม่มี visible catalyst ที่จะ reverse — ยกเว้น: ถ้า AI กลายเป็น tailwind จริง (consulting ช่วย enterprise deploy AI ในสเกลใหญ่) + war de-escalate + valuation washed out พอ อาจ re-rate ได้ แต่ยังไม่เห็นสัญญาณนั้น. company-specific execution แยกจาก sector call — ผู้ที่ pivot ไป outcome-based/managed-service + AI-delivery เร็วที่สุดจะรอด แต่ต้องพิสูจน์ก่อน ไม่ใช่ซื้อล่วงหน้า.",
    keyPoints: [
      "Middle East war กด discretionary spend โดยตรง — ACN CEO Julie Sweet ยืนยันบน Q3 FY26 call; new bookings -2% YoY ($19.3B vs $19.7B), FY26 guide แค่ 3-4% local currency",
      "Structural AI disruption: ตลาดสรุปว่า GenAI = net-negative ต่อ services firms; time-and-materials (ขายชั่วโมงคน) โดนตรงจุด; key risk = 'AI เปลี่ยน economics เร็วกว่าที่ Accenture ปรับตัวได้'",
      "Platform-first shift: 66% ของ enterprise buyer ซื้อ software platform แทนจ้าง integrator; 67% รัน GenAI production แล้ว; เม็ดเงิน AI budget ไหลไป vendor ไม่ใช่ consulting labor arbitrage",
      "Sector-wide ไม่ใช่ ACN-only: Indian IT (INFY/WIT/TCS/CTSH) ร่วงตาม ACN outlook — 'weak Accenture outlook revives fears of AI-led disruption, IT stocks reel'",
      "เชื่อมพอร์ต: ACN ถูก trim 50% แล้ว (stop breach มิ.ย. 2026, Q3 rev miss + guide cut) — sector call ยืนยันปัญหาเป็น structural + cyclical พร้อมกัน ไม่ใช่ company-specific",
      "NEGATIVE สำหรับเงินทุนใหม่: demand อ่อนทั้ง cyclical + structural, regime TRANSITIONAL-CAUTIOUS, ไม่มี visible catalyst reverse — re-rate ได้ถ้า AI พลิกเป็น tailwind + war de-escalate + valuation washed out (ยังไม่เห็นสัญญาณ)",
    ],
    metrics: [
      { label: "ACN new bookings YoY change Q3 FY2026 (%)", value: -2 },
      { label: "ACN FY2026 revenue guide (local currency, midpoint %)", value: 3.5 },
      { label: "Enterprise buyers following platform-first strategy (%)", value: 66 },
      { label: "Organizations running GenAI in production (%)", value: 67 },
    ],
    relatedTickers: ["ACN", "IBM", "INFY", "CTSH", "WIT"],
    sources: [
      { title: "Futurum Group — Can Accenture's Federal Wins Keep Pace with AI-Driven Consulting Disruption?", url: "https://futurumgroup.com/insights/accenture-federal-services-2/" },
      { title: "Staffing Industry Analysts — Accenture's new bookings down 2% on AI disruptions", url: "https://www.staffingindustry.com/news/global-daily-news/accentures-new-bookings-down-2-on-ai-disruptions" },
      { title: "Futunn News — 'AI Disrupts Everything' Sweeps Through IT Consulting and Outsourcing; Accenture Earnings Outlook Falls Short", url: "https://news.futunn.com/en/post/74797797/ai-disrupts-everything-sweeps-through-it-consulting-and-outsourcing-accenture" },
      { title: "Press Insider — Weak Accenture outlook revives fears of AI-led disruption, IT stocks reel", url: "https://pressinsider.com/business/indian-it-stocks-reel-after-accenture-outlook-revives-fears-of-ai-led-disruption/" },
      { title: "Simply Wall St — ACN: High-quality global services company facing an AI-driven valuation reset", url: "https://simplywall.st/community/narratives/us/software/nyse-acn/accenture/7ddmqnto-high-quality-global-services-company-facing-an-ai-driven-valuation-reset-5xnk" },
    ],
    lastUpdated: "2026-09-11",
    author: "Atlas",
    trigger: "Byproduct of Regime re-call 2026-09-11 — direct macro-to-sector linkage discovered (Middle East war → discretionary spend cut → consulting demand), compounding the structural AI-disruption thesis; first dedicated IT Services / Consulting entry, applies beyond ACN to IBM/INFY/CTSH/WIT",
  },
];
